# Estatísticas do artigo

SVM · `l1_stable` · nocombat. ΔAUC pareado (bootstrap) + FDR BH.
Claim: **`48m_6m`**. Corpo: **D `t1_ols` vs T1**, **2v `t1_r10` vs T1**, **3v rates `t1_r10_r21` vs T1**, tetos `four_ceilings` (uni + best late + vol T1 ∪ forma D + all).
Encodings longitudinais sempre usam tempo (÷Δt ou OLS); Δ absolutos (B0/Q4, D21) removidos.
Figs: `6_results.ipynb`.

| § | Pergunta | Ficheiro |
|---|----------|----------|
| 1 | Demografia sMCI vs pMCI (`48m_6m`) | `stats_demo_48m6m` |
| 2 | Idade / sexo / idade+sexo (SVM nested, `5_clinic_img.py --clinical-cols`) vs vol T1 | `stats_confound_48m6m` |
| **3** | **D / R10 / R10R21 vs T1, 5 famílias, FDR** | **`stats_{ols,r10,r10r21}_vs_t1_48m6m`** |
| 4 | Mesmos contrastes × 4 coortes (+ soft False) | `stats_*_vs_t1_gradient` |
| **5** | **Tetos four_ceilings (contrastes pré-spec)** | **`stats_four_ceilings_48m6m`** |
| 6 | Clínico vs vol T1 | `stats_clinic_48m6m` |
| 7 | Soft True vs False (descritivo) | `stats_soft_true_vs_false` |
| 8 | ComBat: T1 NeuroComBat − T1, D longComBat − D, D longComBat − T1 NeuroComBat | `stats_combat_vs_nocombat` |
| 9 | Tabela D — resumo complementares | `stats_table_d_complements` |
| 10 | Sensibilidade α = 1% (uni × 4 coortes + tetos) | `stats_sensitivity_alpha01` |
| 11 | Escolha B/C/D: Friedman (20 blocos) + Wilcoxon D−B, D−C (Holm) | `stats_friedman_bcd_{blocks,posthoc}` |
| 12 | União multiclasse (5 fam.) × 4 coortes: all-D − all-T1, all − uni (+ IC 99%) | `stats_union_4cohorts` |

In [1]:
from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

_MOD = Path.cwd() / "modules"
if str(_MOD) not in sys.path:
    sys.path.insert(0, str(_MOD))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display
from scipy import stats
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from ablation_analysis import explode_patient_predictions, prepare_ablation_df
from stats_compare import (
    apply_bh_fdr,
    clinical_results_path,
    compare_modalities,
    fusion_results_path,
    image_ablation_path,
    paired_comparison_row,
    print_comparison_summary,
)

COHORT_CLAIM = "48m_6m"
COHORTS_GRADIENT = ("36m_6m", "36m_12m", "48m_6m", "48m_12m")
BASE = Path(f"csvs/cohorts/{COHORT_CLAIM}")
LONG_CSV = BASE / "adnimerged_longitudinal.csv"
TABLE_DIR = Path("Artigo 1 pgirardi") / "tables"

PROTOCOL_BASELINE = "t1_only"
PROTOCOL_TWO_VISIT = "t1_r10"  # 2 visitas ÷Δt
PROTOCOL_LONGITUDINAL = "t1_ols"  # 3v método D (primário)
PROTOCOL_LONG_B = "t1_r10_r21"  # 3v taxas consecutivas
MODS_COMPARE = ("vol", "shape", "texture", "disp", "firstorder")
CLINIC_MODALITY = "vol"
SOFT_FALSE_COHORT = "48m_6m_soft_False"
ALPHA = 0.05

LATE_ALL_T1 = "late__t1_vol__t1_shape__t1_texture__t1_disp__t1_firstorder"
LATE_ALL_OLS = (
    "late__t1_ols_vol__t1_ols_shape__t1_ols_texture"
    "__t1_ols_disp__t1_ols_firstorder"
)
LATE_VOL_T1_SHAPE_D = "late__t1_vol__t1_ols_shape"  # âncora vol T1 ∪ forma D

FOLDER_REP = {
    "ablation_results_t1_only": "t1_only",
    "ablation_results_r10": "t1_r10",
    "ablation_results_r10r21": "t1_r10_r21",
    "ablation_results_ols": "t1_ols",
    "ablation_results_rate02": "t1_rate02",
    "ablation_results_ols_longcombat": "t1_ols",
    "ablation_results_combat_t1_only": "t1_only",
    "ablation_results_clinic_img_t1_only": "t1_only",
    "ablation_results_late_fusion": "late_fusion",
}


@dataclass(frozen=True)
class StatsCfg:
    task: str = "smci_pmci"
    groups: tuple[str, str] = ("sMCI", "pMCI")
    positive_group: str = "pMCI"
    modality: str = "vol"
    model_key: str = "svm"
    with_combat: bool = False
    selection_mode: str = "l1_stable"
    protocol: str = "t1_only"
    n_perm: int = 5000
    n_bootstrap: int = 5000
    seed: int = 42


STATS_CFG = StatsCfg()


def ler_p(p: float, *, contexto: str = "") -> str:
    tag = "significativo" if p < ALPHA else "não significativo"
    prefix = f"{contexto}: " if contexto else ""
    return f"{prefix}{tag} (p={p:.4f})"


def save_table(df: pd.DataFrame, name: str) -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    path = TABLE_DIR / f"{name}.csv"
    df.to_csv(path, index=False)
    print("Salvo:", path)


print("claim:", BASE, "| long D:", PROTOCOL_LONGITUDINAL, "| 2v:", PROTOCOL_TWO_VISIT, "vs", PROTOCOL_BASELINE)
print("mods:", MODS_COMPARE, "| model:", STATS_CFG.model_key, STATS_CFG.selection_mode)
print("clinic+img:", CLINIC_MODALITY, "| soft_false:", SOFT_FALSE_COHORT)
print("perm/boot:", STATS_CFG.n_perm, STATS_CFG.n_bootstrap)


claim: csvs/cohorts/48m_6m | long D: t1_ols | 2v: t1_r10 vs t1_only
mods: ('vol', 'shape', 'texture', 'disp', 'firstorder') | model: svm l1_stable
clinic+img: vol | soft_false: 48m_6m_soft_False
perm/boot: 5000 5000


In [2]:
def load_cohort(long_path: Path, cfg: StatsCfg) -> pd.DataFrame:
    sub = pd.read_csv(long_path)
    sub = sub[sub["slot"].astype(str).isin(("baseline", "t0"))]
    sub = sub.sort_values(["ID_PT", "ID_IMG"]).groupby("ID_PT", as_index=False).first()
    sub = sub[sub["GROUP"].isin(cfg.groups)].copy()
    sub["ID_PT"] = sub["ID_PT"].astype(str)
    sub["y"] = (sub["GROUP"] == cfg.positive_group).astype(int)
    sub["SEX_bin"] = sub["SEX"].map({"M": 0, "F": 1, 0: 0, 1: 1})
    return sub


def permutation_auc_p(
    y, scores, *, n_perm: int, seed: int, bidirectional: bool = False,
) -> tuple[float, float]:
    y = np.asarray(y, dtype=int)
    s = np.asarray(scores, dtype=float)
    auc_obs = float(
        max(roc_auc_score(y, s), roc_auc_score(y, -s)) if bidirectional
        else roc_auc_score(y, s)
    )
    prng = np.random.default_rng(seed)
    ge = 0
    for _ in range(n_perm):
        yp = prng.permutation(y)
        auc_n = (
            max(roc_auc_score(yp, s), roc_auc_score(yp, -s)) if bidirectional
            else roc_auc_score(yp, s)
        )
        ge += int(auc_n >= auc_obs)
    return auc_obs, (ge + 1) / (n_perm + 1)


def bootstrap_auc_diff(y, scores_a, scores_b, *, n_boot: int, seed: int):
    y = np.asarray(y, dtype=int)
    a, b = np.asarray(scores_a, float), np.asarray(scores_b, float)
    obs = float(roc_auc_score(y, a) - roc_auc_score(y, b))
    prng = np.random.default_rng(seed)
    diffs = []
    for _ in range(n_boot):
        idx = prng.integers(0, len(y), size=len(y))
        yb, ab, bb = y[idx], a[idx], b[idx]
        if len(np.unique(yb)) < 2:
            continue
        diffs.append(float(roc_auc_score(yb, ab) - roc_auc_score(yb, bb)))
    diffs = np.asarray(diffs)
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    return obs, float(lo), float(hi)


def nested_cv_auc_univariate(X, y, *, seed: int, k: int = 5):
    X = np.asarray(X, dtype=float).reshape(-1, 1)
    y = np.asarray(y, dtype=int)
    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(max_iter=5000, random_state=seed)),
    ])
    cv = StratifiedKFold(k, shuffle=True, random_state=seed)
    scores = cross_val_predict(pipe, X, y, cv=cv, method="predict_proba")[:, 1]
    return float(roc_auc_score(y, scores)), scores


def patient_image_scores(
    path: Path, cfg: StatsCfg, *, expect_representation: str | None = None,
) -> pd.DataFrame:
    raw = prepare_ablation_df(pd.read_csv(path))
    mask = (
        (raw["task"] == cfg.task)
        & (raw["modality"] == cfg.modality)
        & (raw["model_key"] == cfg.model_key)
        & (raw["with_combat"] == cfg.with_combat)
        & (raw["selection_mode"] == cfg.selection_mode)
    )
    if expect_representation is not None and "representation" in raw.columns:
        mask = mask & (raw["representation"].astype(str) == expect_representation)
    sub = raw.loc[mask]
    if sub.empty:
        raise FileNotFoundError(f"sem linhas para {cfg} rep={expect_representation} em {path}")
    pat = explode_patient_predictions(sub)
    return pat.groupby("ID_PT", as_index=False).agg(
        y=("y", "first"), score_img=("score", "mean"),
    )


def patient_scores_from_path(path: Path, cfg: StatsCfg) -> pd.DataFrame:
    expect = None
    names = {p.name for p in path.parents} | {path.parent.name}
    for folder, rep in FOLDER_REP.items():
        if folder in names:
            expect = rep
            break
    return patient_image_scores(
        path, cfg, expect_representation=expect,
    ).rename(columns={"score_img": "score"})


def cfg_for_modality(mod: str, cfg: StatsCfg | None = None, **kw) -> StatsCfg:
    c = cfg or STATS_CFG
    d = {f.name: getattr(c, f.name) for f in StatsCfg.__dataclass_fields__.values()}
    d["modality"] = mod
    d.update(kw)
    return StatsCfg(**d)


def cfg_clinical(cfg: StatsCfg | None = None) -> StatsCfg:
    return cfg_for_modality("clinical", cfg, with_combat=False, selection_mode="none", protocol="clinical")


def compare_encoding_vs_t1(
    base: Path,
    protocol_long: str,
    *,
    label_a: str,
    cfg: StatsCfg | None = None,
    comparison: str | None = None,
) -> pd.DataFrame:
    c = cfg or STATS_CFG
    tag = comparison or f"{base.name}_{protocol_long}_vs_t1_only"
    return compare_modalities(
        MODS_COMPARE,
        path_a=lambda m: image_ablation_path(base, protocol_long, m),
        path_b=lambda m: image_ablation_path(base, PROTOCOL_BASELINE, m),
        cfg_for_mod=lambda m: cfg_for_modality(m, c),
        load_patients=patient_scores_from_path,
        permutation_auc_p=permutation_auc_p,
        n_perm=c.n_perm,
        n_bootstrap=c.n_bootstrap,
        seed=c.seed,
        label_a=label_a,
        label_b="t1_only",
        comparison=tag,
        alpha=ALPHA,
    )


def compare_ols_vs_t1(
    base: Path,
    cfg: StatsCfg | None = None,
    *,
    comparison: str | None = None,
) -> pd.DataFrame:
    """Método D (t1_ols) vs baseline."""
    return compare_encoding_vs_t1(
        base,
        PROTOCOL_LONGITUDINAL,
        label_a="ols",
        cfg=cfg,
        comparison=comparison or f"{base.name}_t1_ols_vs_t1_only",
    )


def compare_r10_vs_t1(
    base: Path,
    cfg: StatsCfg | None = None,
    *,
    comparison: str | None = None,
) -> pd.DataFrame:
    """2 visitas ÷Δt (t1_r10) vs baseline."""
    return compare_encoding_vs_t1(
        base,
        PROTOCOL_TWO_VISIT,
        label_a="r10",
        cfg=cfg,
        comparison=comparison or f"{base.name}_t1_r10_vs_t1_only",
    )


def compare_r10r21_vs_t1(
    base: Path,
    cfg: StatsCfg | None = None,
    *,
    comparison: str | None = None,
) -> pd.DataFrame:
    """3v taxas consecutivas (t1_r10_r21 = B) vs baseline."""
    return compare_encoding_vs_t1(
        base,
        PROTOCOL_LONG_B,
        label_a="r10r21",
        cfg=cfg,
        comparison=comparison or f"{base.name}_t1_r10_r21_vs_t1_only",
    )


def combat_ablation_path(base: Path, protocol: str, modality: str) -> Path:
    roots = {
        "t1_only": base / "ablation_results_combat_t1_only",
    }
    if protocol not in roots:
        raise KeyError(f"protocolo combat desconhecido: {protocol}")
    return roots[protocol] / modality / "ablation_results_all.csv"


def patient_auc(path: Path, cfg: StatsCfg) -> tuple[float, int]:
    pat = patient_scores_from_path(path, cfg)
    return float(roc_auc_score(pat["y"], pat["score"])), int(len(pat))


cohort = load_cohort(LONG_CSV, STATS_CFG)
g0, g1 = STATS_CFG.groups
print(f"{BASE.name}: n={len(cohort)} | {cohort['GROUP'].value_counts().to_dict()}")


48m_6m: n=193 | {'pMCI': 120, 'sMCI': 73}


## 1. Demografia — `48m_6m`

Idade (Mann-Whitney) e sexo (χ²) entre sMCI e pMCI.


In [3]:
age_a = cohort.loc[cohort["GROUP"] == g0, "AGE"].dropna()
age_b = cohort.loc[cohort["GROUP"] == g1, "AGE"].dropna()
_, p_age_groups = stats.mannwhitneyu(age_a, age_b, alternative="two-sided")
sex_tab = pd.crosstab(
    cohort["GROUP"], cohort["SEX_bin"], rownames=["GROUP"], colnames=["SEX (0=M, 1=F)"],
)
_, p_sex_groups, _, _ = stats.chi2_contingency(sex_tab)
demo = pd.DataFrame([
    {
        "variavel": "idade", "teste": "Mann-Whitney U",
        "media_sMCI": float(age_a.mean()), "media_pMCI": float(age_b.mean()),
        "p": p_age_groups,
    },
    {
        "variavel": "sexo", "teste": "chi2",
        "prop_F_sMCI": float(cohort.loc[cohort["GROUP"] == g0, "SEX_bin"].mean()),
        "prop_F_pMCI": float(cohort.loc[cohort["GROUP"] == g1, "SEX_bin"].mean()),
        "p": p_sex_groups,
    },
])
save_table(demo, "stats_demo_48m6m")
display(sex_tab)
display(demo.round(4))
print(ler_p(p_age_groups, contexto="Idade"))
print(ler_p(p_sex_groups, contexto="Sexo"))


Salvo: Artigo 1 pgirardi/tables/stats_demo_48m6m.csv


"SEX (0=M, 1=F)",0,1
GROUP,,
pMCI,62,58
sMCI,48,25


,variavel,teste,media_sMCI,media_pMCI,p,prop_F_sMCI,prop_F_pMCI
0,idade,Mann-Whitney U,72.2877,74.35,0.0624,NaN,NaN
1,sexo,chi2,NaN,NaN,0.0772,0.3425,0.4833


Idade: não significativo (p=0.0624)
Sexo: não significativo (p=0.0772)


## 2. Idade/sexo vs imagem (vol T1)

Mesmo protocolo do claim (SVM, CV aninhada 5×10, Optuna 10, sem seleção). Escores OOF gerados por:

```bash
for c in AGE SEX SEX,AGE; do
  python 5_clinic_img.py --cohort 48m_6m --feature-set clinical --tasks smci_pmci --models svm \
    --repeats 10 --tuner optuna --optuna-trials 10 --clinical-cols $c
done
```

Permutação por modelo; ΔAUC bootstrap pareado: vol T1 − demografia.


In [4]:
cfg = STATS_CFG
CLIN_DIR = BASE / "ablation_results_clinic"
DEMO_TAGS = {"age": "idade", "sex": "sexo", "sex_age": "idade+sexo"}

img = patient_image_scores(
    image_ablation_path(BASE, PROTOCOL_BASELINE, "vol"), cfg, expect_representation="t1_only",
).rename(columns={"score_img": "score_a"})

rows = []
for k, (tag, lab) in enumerate(DEMO_TAGS.items()):
    demo = patient_image_scores(CLIN_DIR / f"clinical_{tag}_results_all.csv", cfg_clinical(cfg))
    paired = img.merge(demo.rename(columns={"score_img": "score_b"}), on=["ID_PT", "y"])
    assert len(paired) == len(img), f"{tag}: {len(paired)} pares vs {len(img)} (IDs diferentes)"
    row = paired_comparison_row(
        paired, score_a="score_a", score_b="score_b", label_a="vol_t1", label_b="demo",
        n_boot=cfg.n_bootstrap, seed=cfg.seed + 200 + 10 * k,
        permutation_auc_p=permutation_auc_p, n_perm=cfg.n_perm, alpha=ALPHA,
    )
    row.update({"demo": lab, "modality": f"vol T1 − {lab}"})
    rows.append(row)

confound = pd.DataFrame(rows)
save_table(confound, "stats_confound_48m6m")
display(confound.round(4))
for _, r in confound.iterrows():
    print(f"{r['demo']:<11} AUC={r['auc_demo']:.3f} ({ler_p(r['p_perm_demo'], contexto='perm')})  "
          f"vol T1 − {r['demo']}: Δ={r['delta_auc']:.3f} [{r['ci95_lo']:.3f}, {r['ci95_hi']:.3f}]")
print(f"vol T1 AUC={confound['auc_vol_t1'].iloc[0]:.3f} n={len(img)}")


Salvo: Artigo 1 pgirardi/tables/stats_confound_48m6m.csv


,n_pacientes,auc_vol_t1,auc_demo,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,vol_t1_superior,p_perm_vol_t1,p_perm_demo,significant_fdr,significant_raw,demo,modality
0,193,0.7559,0.3953,0.3606,0.2401,0.4742,0.0002,0.0004,True,0.0002,0.9946,False,True,idade,vol T1 − idade
1,193,0.7559,0.4631,0.2928,0.1778,0.4072,0.0002,0.0004,True,0.0002,0.8010,False,True,sexo,vol T1 − sexo
2,193,0.7559,0.5422,0.2137,0.1011,0.3216,0.0002,0.0004,True,0.0002,0.1722,False,True,idade+sexo,vol T1 − idade+sexo


idade       AUC=0.395 (perm: não significativo (p=0.9946))  vol T1 − idade: Δ=0.361 [0.240, 0.474]
sexo        AUC=0.463 (perm: não significativo (p=0.8010))  vol T1 − sexo: Δ=0.293 [0.178, 0.407]
idade+sexo  AUC=0.542 (perm: não significativo (p=0.1722))  vol T1 − idade+sexo: Δ=0.214 [0.101, 0.322]
vol T1 AUC=0.756 n=193


## 3. Claim — D / 2v / 3v-rates vs T1 em `48m_6m`

Pareado por paciente. H1 one-sided: AUC(encoding) > AUC(T1).
FDR BH nas 5 famílias **dentro** de cada contraste.


In [5]:
cfg = STATS_CFG
print("D (ols):", image_ablation_path(BASE, PROTOCOL_LONGITUDINAL, "vol").parent.parent.name)
print("2v (r10):", image_ablation_path(BASE, PROTOCOL_TWO_VISIT, "vol").parent.parent.name)
print("3v rates:", image_ablation_path(BASE, PROTOCOL_LONG_B, "vol").parent.parent.name)
print("T1:", image_ablation_path(BASE, PROTOCOL_BASELINE, "vol").parent.parent.name)
print("mods:", MODS_COMPARE)

cmp_claim_ols = compare_ols_vs_t1(BASE, cfg, comparison=f"{COHORT_CLAIM}_t1_ols_vs_t1_only")
save_table(cmp_claim_ols, "stats_ols_vs_t1_48m6m")
print(f"\nClaim | {COHORT_CLAIM} | t1_ols vs t1_only | {cfg.task} | {cfg.model_key}\n")
display(cmp_claim_ols.round(4))
print("\n── ΔAUC = D(ols) − T1; FDR ──")
print_comparison_summary(cmp_claim_ols, label_a="ols", label_b="t1_only")

cmp_claim_r10 = compare_r10_vs_t1(BASE, cfg, comparison=f"{COHORT_CLAIM}_t1_r10_vs_t1_only")
save_table(cmp_claim_r10, "stats_r10_vs_t1_48m6m")
print(f"\nClaim | {COHORT_CLAIM} | t1_r10 vs t1_only | {cfg.task} | {cfg.model_key}\n")
display(cmp_claim_r10.round(4))
print("\n── ΔAUC = 2v(r10) − T1; FDR ──")
print_comparison_summary(cmp_claim_r10, label_a="r10", label_b="t1_only")

cmp_claim_r10r21 = compare_r10r21_vs_t1(BASE, cfg, comparison=f"{COHORT_CLAIM}_t1_r10_r21_vs_t1_only")
save_table(cmp_claim_r10r21, "stats_r10r21_vs_t1_48m6m")
print(f"\nClaim | {COHORT_CLAIM} | t1_r10_r21 vs t1_only | {cfg.task} | {cfg.model_key}\n")
display(cmp_claim_r10r21.round(4))
print("\n── ΔAUC = 3v rates − T1; FDR ──")
print_comparison_summary(cmp_claim_r10r21, label_a="r10r21", label_b="t1_only")

for name, cmp, la in (
    ("D(ols)", cmp_claim_ols, "ols"),
    ("2v(r10)", cmp_claim_r10, "r10"),
    ("3v rates", cmp_claim_r10r21, "r10r21"),
):
    if cmp.empty:
        continue
    print(f"\n── Mapa {name} ──")
    for _, r in cmp.iterrows():
        tag = "FDR+" if r["significant_fdr"] else ("raw+" if r["significant_raw"] else "n.s.")
        print(
            f"  {r['modality']}: {name}={r[f'auc_{la}']:.3f}  T1={r['auc_t1_only']:.3f}  "
            f"Δ={r['delta_auc']:+.3f}  [{r['ci95_lo']:.3f}, {r['ci95_hi']:.3f}]  → {tag}"
        )


D (ols): ablation_results_ols
2v (r10): ablation_results_r10
3v rates: ablation_results_r10r21
T1: ablation_results_t1_only
mods: ('vol', 'shape', 'texture', 'disp', 'firstorder')
Salvo: Artigo 1 pgirardi/tables/stats_ols_vs_t1_48m6m.csv

Claim | 48m_6m | t1_ols vs t1_only | smci_pmci | svm



,n_pacientes,auc_ols,auc_t1_only,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,ols_superior,p_perm_ols,p_perm_t1_only,significant_fdr,significant_raw,modality,comparison,p_fdr_bh
0,193,0.7838,0.7559,0.0279,-0.0131,0.0698,0.0900,0.1800,False,0.0002,0.0002,False,False,vol,48m_6m_t1_ols_vs_t1_only,0.2250
1,193,0.7282,0.7115,0.0167,-0.0216,0.0542,0.1860,0.3719,False,0.0002,0.0002,False,False,shape,48m_6m_t1_ols_vs_t1_only,0.3099
2,193,0.6080,0.6276,-0.0196,-0.0507,0.0137,0.8834,0.2332,False,0.0056,0.0016,False,False,texture,48m_6m_t1_ols_vs_t1_only,0.8834
3,193,0.5732,0.5404,0.0328,-0.0051,0.0707,0.0462,0.0924,False,0.0438,0.1762,False,False,disp,48m_6m_t1_ols_vs_t1_only,0.2250
4,193,0.6918,0.6865,0.0053,-0.0219,0.0335,0.3617,0.7235,False,0.0002,0.0002,False,False,firstorder,48m_6m_t1_ols_vs_t1_only,0.4522



── ΔAUC = D(ols) − T1; FDR ──
  vol: ΔAUC=0.028 [-0.013, 0.070]  p=0.0900  q=0.2250  → sem evidência
  shape: ΔAUC=0.017 [-0.022, 0.054]  p=0.1860  q=0.3099  → sem evidência
  texture: ΔAUC=-0.020 [-0.051, 0.014]  p=0.8834  q=0.8834  → sem evidência
  disp: ΔAUC=0.033 [-0.005, 0.071]  p=0.0462  q=0.2250  → sem evidência
  firstorder: ΔAUC=0.005 [-0.022, 0.033]  p=0.3617  q=0.4522  → sem evidência
Salvo: Artigo 1 pgirardi/tables/stats_r10_vs_t1_48m6m.csv

Claim | 48m_6m | t1_r10 vs t1_only | smci_pmci | svm



,n_pacientes,auc_r10,auc_t1_only,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,r10_superior,p_perm_r10,p_perm_t1_only,significant_fdr,significant_raw,modality,comparison,p_fdr_bh
0,193,0.7405,0.7559,-0.0154,-0.0374,0.0049,0.9264,0.1472,False,0.0002,0.0002,False,False,vol,48m_6m_t1_r10_vs_t1_only,0.9264
1,193,0.7097,0.7115,-0.0018,-0.0311,0.0288,0.5451,0.9098,False,0.0002,0.0002,False,False,shape,48m_6m_t1_r10_vs_t1_only,0.6814
2,193,0.6704,0.6276,0.0428,-0.0242,0.1080,0.1088,0.2176,False,0.0002,0.0016,False,False,texture,48m_6m_t1_r10_vs_t1_only,0.5439
3,193,0.5503,0.5404,0.0099,-0.0225,0.0427,0.2769,0.5539,False,0.1240,0.1762,False,False,disp,48m_6m_t1_r10_vs_t1_only,0.6199
4,193,0.6894,0.6865,0.0029,-0.0135,0.0194,0.3719,0.7439,False,0.0002,0.0002,False,False,firstorder,48m_6m_t1_r10_vs_t1_only,0.6199



── ΔAUC = 2v(r10) − T1; FDR ──
  vol: ΔAUC=-0.015 [-0.037, 0.005]  p=0.9264  q=0.9264  → sem evidência
  shape: ΔAUC=-0.002 [-0.031, 0.029]  p=0.5451  q=0.6814  → sem evidência
  texture: ΔAUC=0.043 [-0.024, 0.108]  p=0.1088  q=0.5439  → sem evidência
  disp: ΔAUC=0.010 [-0.023, 0.043]  p=0.2769  q=0.6199  → sem evidência
  firstorder: ΔAUC=0.003 [-0.014, 0.019]  p=0.3719  q=0.6199  → sem evidência
Salvo: Artigo 1 pgirardi/tables/stats_r10r21_vs_t1_48m6m.csv

Claim | 48m_6m | t1_r10_r21 vs t1_only | smci_pmci | svm



,n_pacientes,auc_r10r21,auc_t1_only,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,r10r21_superior,p_perm_r10r21,p_perm_t1_only,significant_fdr,significant_raw,modality,comparison,p_fdr_bh
0,193,0.7764,0.7559,0.0204,-0.0228,0.0649,0.1762,0.3523,False,0.0002,0.0002,False,False,vol,48m_6m_t1_r10_r21_vs_t1_only,0.2979
1,193,0.7182,0.7115,0.0066,-0.0327,0.0460,0.3527,0.7055,False,0.0002,0.0002,False,False,shape,48m_6m_t1_r10_r21_vs_t1_only,0.4387
2,193,0.6695,0.6276,0.0419,-0.0238,0.1073,0.1084,0.2168,False,0.0002,0.0016,False,False,texture,48m_6m_t1_r10_r21_vs_t1_only,0.2979
3,193,0.5589,0.5404,0.0185,-0.0202,0.0562,0.1788,0.3575,False,0.0854,0.1762,False,False,disp,48m_6m_t1_r10_r21_vs_t1_only,0.2979
4,193,0.6888,0.6865,0.0023,-0.0229,0.0296,0.4387,0.8774,False,0.0002,0.0002,False,False,firstorder,48m_6m_t1_r10_r21_vs_t1_only,0.4387



── ΔAUC = 3v rates − T1; FDR ──
  vol: ΔAUC=0.020 [-0.023, 0.065]  p=0.1762  q=0.2979  → sem evidência
  shape: ΔAUC=0.007 [-0.033, 0.046]  p=0.3527  q=0.4387  → sem evidência
  texture: ΔAUC=0.042 [-0.024, 0.107]  p=0.1084  q=0.2979  → sem evidência
  disp: ΔAUC=0.018 [-0.020, 0.056]  p=0.1788  q=0.2979  → sem evidência
  firstorder: ΔAUC=0.002 [-0.023, 0.030]  p=0.4387  q=0.4387  → sem evidência

── Mapa D(ols) ──
  vol: D(ols)=0.784  T1=0.756  Δ=+0.028  [-0.013, 0.070]  → n.s.
  shape: D(ols)=0.728  T1=0.712  Δ=+0.017  [-0.022, 0.054]  → n.s.
  texture: D(ols)=0.608  T1=0.628  Δ=-0.020  [-0.051, 0.014]  → n.s.
  disp: D(ols)=0.573  T1=0.540  Δ=+0.033  [-0.005, 0.071]  → n.s.
  firstorder: D(ols)=0.692  T1=0.687  Δ=+0.005  [-0.022, 0.033]  → n.s.

── Mapa 2v(r10) ──
  vol: 2v(r10)=0.741  T1=0.756  Δ=-0.015  [-0.037, 0.005]  → n.s.
  shape: 2v(r10)=0.710  T1=0.712  Δ=-0.002  [-0.031, 0.029]  → n.s.
  texture: 2v(r10)=0.670  T1=0.628  Δ=+0.043  [-0.024, 0.108]  → n.s.
  disp: 2v(r10)=

## 4. Gradiente — D vs T1 e R10 vs T1 × 4 coortes (+ soft False)

Células sobrepõem sujeitos. `36m_12m` inverte (pMCI n=33). Não é réplica.
FDR **dentro** de cada coorte × contraste (5 famílias).


In [6]:
cfg = STATS_CFG
cols = [
    "cohort", "modality", "n_pacientes",
    "auc_long", "auc_t1_only", "delta_auc",
    "ci95_lo", "ci95_hi", "p_bootstrap_one_sided", "p_fdr_bh",
    "significant_raw", "significant_fdr", "contrast",
]


def _gradient(contrast: str, runner, label_a: str, cache_claim):
    rows = []
    for cname in COHORTS_GRADIENT:
        base = Path(f"csvs/cohorts/{cname}")
        if cname == COHORT_CLAIM and cache_claim is not None and not cache_claim.empty:
            cmp = cache_claim.copy()
        else:
            cmp = runner(base, cfg, comparison=f"{cname}_{contrast}")
            if cmp.empty:
                print(f"SKIP {cname} | {contrast}")
                continue
        cmp = cmp.copy()
        cmp["cohort"] = cname
        cmp["contrast"] = contrast
        cmp["auc_long"] = cmp[f"auc_{label_a}"]
        rows.append(cmp)
        print(f"\n=== {cname} | {contrast} ===")
        print_comparison_summary(cmp, label_a=label_a, label_b="t1_only")
    return pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()


cmp_gradient_ols = _gradient(
    "t1_ols_vs_t1_only", compare_ols_vs_t1, "ols",
    cmp_claim_ols if "cmp_claim_ols" in dir() else None,
)
if not cmp_gradient_ols.empty:
    save_table(cmp_gradient_ols[cols], "stats_ols_vs_t1_gradient")
    display(cmp_gradient_ols[cols].round(4))
    print("\n── pivot ΔAUC D(ols)−T1 ──")
    display(
        cmp_gradient_ols.pivot(index="modality", columns="cohort", values="delta_auc")
        .reindex(index=list(MODS_COMPARE), columns=list(COHORTS_GRADIENT))
        .round(4)
    )

cmp_gradient_r10 = _gradient(
    "t1_r10_vs_t1_only", compare_r10_vs_t1, "r10",
    cmp_claim_r10 if "cmp_claim_r10" in dir() else None,
)
if not cmp_gradient_r10.empty:
    save_table(cmp_gradient_r10[cols], "stats_r10_vs_t1_gradient")
    display(cmp_gradient_r10[cols].round(4))
    print("\n── pivot ΔAUC 2v(r10)−T1 ──")
    display(
        cmp_gradient_r10.pivot(index="modality", columns="cohort", values="delta_auc")
        .reindex(index=list(MODS_COMPARE), columns=list(COHORTS_GRADIENT))
        .round(4)
    )

cmp_gradient_r10r21 = _gradient(
    "t1_r10_r21_vs_t1_only", compare_r10r21_vs_t1, "r10r21",
    cmp_claim_r10r21 if "cmp_claim_r10r21" in dir() else None,
)
if not cmp_gradient_r10r21.empty:
    save_table(cmp_gradient_r10r21[cols], "stats_r10r21_vs_t1_gradient")
    display(cmp_gradient_r10r21[cols].round(4))
    print("\n── pivot ΔAUC 3v rates−T1 ──")
    display(
        cmp_gradient_r10r21.pivot(index="modality", columns="cohort", values="delta_auc")
        .reindex(index=list(MODS_COMPARE), columns=list(COHORTS_GRADIENT))
        .round(4)
    )

# soft False — mesmos contrastes (descritivo / sensibilidade)
base_soft = Path(f"csvs/cohorts/{SOFT_FALSE_COHORT}")
cmp_soft_ols = compare_ols_vs_t1(base_soft, cfg, comparison=f"{SOFT_FALSE_COHORT}_t1_ols_vs_t1_only")
if not cmp_soft_ols.empty:
    save_table(cmp_soft_ols, "stats_ols_vs_t1_soft_False")
    print(f"\n=== {SOFT_FALSE_COHORT} | t1_ols vs t1_only ===")
    print_comparison_summary(cmp_soft_ols, label_a="ols", label_b="t1_only")

cmp_soft_r10 = compare_r10_vs_t1(base_soft, cfg, comparison=f"{SOFT_FALSE_COHORT}_t1_r10_vs_t1_only")
if not cmp_soft_r10.empty:
    save_table(cmp_soft_r10, "stats_r10_vs_t1_soft_False")
    print(f"\n=== {SOFT_FALSE_COHORT} | t1_r10 vs t1_only ===")
    print_comparison_summary(cmp_soft_r10, label_a="r10", label_b="t1_only")

cmp_soft_r10r21 = compare_r10r21_vs_t1(base_soft, cfg, comparison=f"{SOFT_FALSE_COHORT}_t1_r10_r21_vs_t1_only")
if not cmp_soft_r10r21.empty:
    save_table(cmp_soft_r10r21, "stats_r10r21_vs_t1_soft_False")
    print(f"\n=== {SOFT_FALSE_COHORT} | t1_r10_r21 vs t1_only ===")
    print_comparison_summary(cmp_soft_r10r21, label_a="r10r21", label_b="t1_only")



=== 36m_6m | t1_ols_vs_t1_only ===
  vol: ΔAUC=0.025 [-0.014, 0.063]  p=0.1062  q=0.2645  → sem evidência
  shape: ΔAUC=0.011 [-0.024, 0.044]  p=0.2645  q=0.2645  → sem evidência
  texture: ΔAUC=0.055 [0.005, 0.104]  p=0.0160  q=0.0800  → raw sig.
  disp: ΔAUC=0.013 [-0.023, 0.048]  p=0.2484  q=0.2645  → sem evidência
  firstorder: ΔAUC=0.012 [-0.014, 0.040]  p=0.1868  q=0.2645  → sem evidência

=== 36m_12m | t1_ols_vs_t1_only ===
  vol: ΔAUC=0.018 [-0.062, 0.094]  p=0.3139  q=0.5232  → sem evidência
  shape: ΔAUC=0.036 [-0.040, 0.109]  p=0.1704  q=0.4584  → sem evidência
  texture: ΔAUC=0.036 [-0.039, 0.116]  p=0.1834  q=0.4584  → sem evidência
  disp: ΔAUC=-0.030 [-0.094, 0.036]  p=0.8104  q=0.8190  → sem evidência
  firstorder: ΔAUC=-0.031 [-0.095, 0.039]  p=0.8190  q=0.8190  → sem evidência

=== 48m_6m | t1_ols_vs_t1_only ===
  vol: ΔAUC=0.028 [-0.013, 0.070]  p=0.0900  q=0.2250  → sem evidência
  shape: ΔAUC=0.017 [-0.022, 0.054]  p=0.1860  q=0.3099  → sem evidência
  texture: ΔA

,cohort,modality,n_pacientes,auc_long,auc_t1_only,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_fdr_bh,significant_raw,significant_fdr,contrast
0,36m_6m,vol,231,0.7901,0.7656,0.0245,-0.0137,0.0627,0.1062,0.2645,False,False,t1_ols_vs_t1_only
1,36m_6m,shape,231,0.7435,0.7329,0.0106,-0.0238,0.0437,0.2645,0.2645,False,False,t1_ols_vs_t1_only
2,36m_6m,texture,231,0.6732,0.6186,0.0546,0.0047,0.1036,0.0160,0.0800,True,False,t1_ols_vs_t1_only
3,36m_6m,disp,231,0.6080,0.5955,0.0125,-0.0230,0.0480,0.2484,0.2645,False,False,t1_ols_vs_t1_only
4,36m_6m,firstorder,231,0.6661,0.6538,0.0123,-0.0142,0.0397,0.1868,0.2645,False,False,t1_ols_vs_t1_only
5,36m_12m,vol,154,0.7080,0.6900,0.0180,-0.0617,0.0945,0.3139,0.5232,False,False,t1_ols_vs_t1_only
6,36m_12m,shape,154,0.7160,0.6804,0.0356,-0.0401,0.1089,0.1704,0.4584,False,False,t1_ols_vs_t1_only
7,36m_12m,texture,154,0.5357,0.4996,0.0361,-0.0386,0.1159,0.1834,0.4584,False,False,t1_ols_vs_t1_only
8,36m_12m,disp,154,0.3887,0.4182,-0.0296,-0.0944,0.0362,0.8104,0.8190,False,False,t1_ols_vs_t1_only
9,36m_12m,firstorder,154,0.5675,0.5983,-0.0308,-0.0950,0.0391,0.8190,0.8190,False,False,t1_ols_vs_t1_only



── pivot ΔAUC D(ols)−T1 ──


cohort,36m_6m,36m_12m,48m_6m,48m_12m
modality,,,,
vol,0.0245,0.0180,0.0279,0.1331
shape,0.0106,0.0356,0.0167,-0.0014
texture,0.0546,0.0361,-0.0196,0.0793
disp,0.0125,-0.0296,0.0328,-0.0052
firstorder,0.0123,-0.0308,0.0053,0.0365



=== 36m_6m | t1_r10_vs_t1_only ===
  vol: ΔAUC=-0.017 [-0.033, -0.002]  p=0.9864  q=0.9864  → sem evidência
  shape: ΔAUC=0.014 [-0.015, 0.044]  p=0.1738  q=0.3463  → sem evidência
  texture: ΔAUC=0.076 [0.012, 0.143]  p=0.0090  q=0.0450  → FDR sig.
  disp: ΔAUC=0.004 [-0.029, 0.037]  p=0.3939  q=0.4924  → sem evidência
  firstorder: ΔAUC=0.008 [-0.011, 0.028]  p=0.2078  q=0.3463  → sem evidência

=== 36m_12m | t1_r10_vs_t1_only ===
  vol: ΔAUC=0.036 [-0.034, 0.108]  p=0.1576  q=0.3939  → sem evidência
  shape: ΔAUC=0.015 [-0.035, 0.066]  p=0.2919  q=0.4866  → sem evidência
  texture: ΔAUC=0.049 [-0.023, 0.121]  p=0.0866  q=0.3939  → sem evidência
  disp: ΔAUC=-0.072 [-0.137, -0.010]  p=0.9910  q=0.9910  → sem evidência
  firstorder: ΔAUC=-0.042 [-0.099, 0.018]  p=0.9236  q=0.9910  → sem evidência

=== 48m_6m | t1_r10_vs_t1_only ===
  vol: ΔAUC=-0.015 [-0.037, 0.005]  p=0.9264  q=0.9264  → sem evidência
  shape: ΔAUC=-0.002 [-0.031, 0.029]  p=0.5451  q=0.6814  → sem evidência
  textur

,cohort,modality,n_pacientes,auc_long,auc_t1_only,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_fdr_bh,significant_raw,significant_fdr,contrast
0,36m_6m,vol,231,0.7488,0.7656,-0.0168,-0.0325,-0.0015,0.9864,0.9864,False,False,t1_r10_vs_t1_only
1,36m_6m,shape,231,0.7464,0.7329,0.0135,-0.0146,0.0438,0.1738,0.3463,False,False,t1_r10_vs_t1_only
2,36m_6m,texture,231,0.6948,0.6186,0.0762,0.0123,0.1428,0.0090,0.0450,True,True,t1_r10_vs_t1_only
3,36m_6m,disp,231,0.5998,0.5955,0.0043,-0.0288,0.0369,0.3939,0.4924,False,False,t1_r10_vs_t1_only
4,36m_6m,firstorder,231,0.6617,0.6538,0.0078,-0.0110,0.0278,0.2078,0.3463,False,False,t1_r10_vs_t1_only
5,36m_12m,vol,154,0.7258,0.6900,0.0358,-0.0341,0.1085,0.1576,0.3939,False,False,t1_r10_vs_t1_only
6,36m_12m,shape,154,0.6950,0.6804,0.0145,-0.0347,0.0657,0.2919,0.4866,False,False,t1_r10_vs_t1_only
7,36m_12m,texture,154,0.5487,0.4996,0.0491,-0.0229,0.1215,0.0866,0.3939,False,False,t1_r10_vs_t1_only
8,36m_12m,disp,154,0.3459,0.4182,-0.0724,-0.1366,-0.0105,0.9910,0.9910,False,False,t1_r10_vs_t1_only
9,36m_12m,firstorder,154,0.5560,0.5983,-0.0423,-0.0991,0.0184,0.9236,0.9910,False,False,t1_r10_vs_t1_only



── pivot ΔAUC 2v(r10)−T1 ──


cohort,36m_6m,36m_12m,48m_6m,48m_12m
modality,,,,
vol,-0.0168,0.0358,-0.0154,0.0399
shape,0.0135,0.0145,-0.0018,-0.0026
texture,0.0762,0.0491,0.0428,-0.0906
disp,0.0043,-0.0724,0.0099,0.0032
firstorder,0.0078,-0.0423,0.0029,-0.0023



=== 36m_6m | t1_r10_r21_vs_t1_only ===
  vol: ΔAUC=0.006 [-0.028, 0.038]  p=0.3707  q=0.4634  → sem evidência
  shape: ΔAUC=0.008 [-0.026, 0.041]  p=0.3197  q=0.4634  → sem evidência
  texture: ΔAUC=0.060 [-0.006, 0.125]  p=0.0382  q=0.1910  → sem evidência
  disp: ΔAUC=-0.005 [-0.043, 0.033]  p=0.6009  q=0.6009  → sem evidência
  firstorder: ΔAUC=0.013 [-0.015, 0.042]  p=0.1982  q=0.4634  → sem evidência

=== 36m_12m | t1_r10_r21_vs_t1_only ===
  vol: ΔAUC=-0.005 [-0.079, 0.071]  p=0.5353  q=0.8818  → sem evidência
  shape: ΔAUC=0.045 [-0.013, 0.107]  p=0.0664  q=0.3319  → sem evidência
  texture: ΔAUC=0.027 [-0.058, 0.114]  p=0.2603  q=0.6509  → sem evidência
  disp: ΔAUC=-0.061 [-0.139, 0.014]  p=0.9426  q=0.9426  → sem evidência
  firstorder: ΔAUC=-0.024 [-0.111, 0.069]  p=0.7055  q=0.8818  → sem evidência

=== 48m_6m | t1_r10_r21_vs_t1_only ===
  vol: ΔAUC=0.020 [-0.023, 0.065]  p=0.1762  q=0.2979  → sem evidência
  shape: ΔAUC=0.007 [-0.033, 0.046]  p=0.3527  q=0.4387  → sem evi

,cohort,modality,n_pacientes,auc_long,auc_t1_only,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_fdr_bh,significant_raw,significant_fdr,contrast
0,36m_6m,vol,231,0.7715,0.7656,0.0059,-0.0278,0.0385,0.3707,0.4634,False,False,t1_r10_r21_vs_t1_only
1,36m_6m,shape,231,0.7413,0.7329,0.0084,-0.0257,0.0412,0.3197,0.4634,False,False,t1_r10_r21_vs_t1_only
2,36m_6m,texture,231,0.6789,0.6186,0.0602,-0.0060,0.1253,0.0382,0.1910,False,False,t1_r10_r21_vs_t1_only
3,36m_6m,disp,231,0.5903,0.5955,-0.0052,-0.0426,0.0325,0.6009,0.6009,False,False,t1_r10_r21_vs_t1_only
4,36m_6m,firstorder,231,0.6666,0.6538,0.0128,-0.0153,0.0425,0.1982,0.4634,False,False,t1_r10_r21_vs_t1_only
5,36m_12m,vol,154,0.6854,0.6900,-0.0045,-0.0790,0.0708,0.5353,0.8818,False,False,t1_r10_r21_vs_t1_only
6,36m_12m,shape,154,0.7258,0.6804,0.0453,-0.0132,0.1066,0.0664,0.3319,False,False,t1_r10_r21_vs_t1_only
7,36m_12m,texture,154,0.5267,0.4996,0.0270,-0.0577,0.1137,0.2603,0.6509,False,False,t1_r10_r21_vs_t1_only
8,36m_12m,disp,154,0.3574,0.4182,-0.0609,-0.1388,0.0141,0.9426,0.9426,False,False,t1_r10_r21_vs_t1_only
9,36m_12m,firstorder,154,0.5740,0.5983,-0.0243,-0.1114,0.0687,0.7055,0.8818,False,False,t1_r10_r21_vs_t1_only



── pivot ΔAUC 3v rates−T1 ──


cohort,36m_6m,36m_12m,48m_6m,48m_12m
modality,,,,
vol,0.0059,-0.0045,0.0204,0.0848
shape,0.0084,0.0453,0.0066,0.0055
texture,0.0602,0.0270,0.0419,0.0382
disp,-0.0052,-0.0609,0.0185,-0.0431
firstorder,0.0128,-0.0243,0.0023,0.0122


Salvo: Artigo 1 pgirardi/tables/stats_ols_vs_t1_soft_False.csv

=== 48m_6m_soft_False | t1_ols vs t1_only ===
  vol: ΔAUC=-0.006 [-0.044, 0.031]  p=0.6173  q=0.8851  → sem evidência
  shape: ΔAUC=-0.002 [-0.034, 0.030]  p=0.5463  q=0.8851  → sem evidência
  texture: ΔAUC=-0.041 [-0.086, 0.000]  p=0.9740  q=0.9740  → sem evidência
  disp: ΔAUC=0.021 [-0.038, 0.081]  p=0.2450  q=0.8851  → sem evidência
  firstorder: ΔAUC=-0.010 [-0.046, 0.025]  p=0.7081  q=0.8851  → sem evidência
Salvo: Artigo 1 pgirardi/tables/stats_r10_vs_t1_soft_False.csv

=== 48m_6m_soft_False | t1_r10 vs t1_only ===
  vol: ΔAUC=0.002 [-0.020, 0.026]  p=0.4201  q=0.5484  → sem evidência
  shape: ΔAUC=0.001 [-0.019, 0.022]  p=0.4387  q=0.5484  → sem evidência
  texture: ΔAUC=0.010 [-0.066, 0.087]  p=0.3831  q=0.5484  → sem evidência
  disp: ΔAUC=0.028 [-0.024, 0.078]  p=0.1510  q=0.5484  → sem evidência
  firstorder: ΔAUC=-0.038 [-0.066, -0.011]  p=0.9974  q=0.9974  → sem evidência
Salvo: Artigo 1 pgirardi/tables/stat

## 5. Tetos `four_ceilings` — contrastes bootstrap pareados (claim)

Scores paciente; uni = argmax família no encoding. Late = argmax grelha (T1-only vs mistura D). FDR BH na lista pré-especificada (7 contrastes = barras de `four_ceilings_48m6m`). R10 vs T1 fica no §3 (por família).

| Contraste | H1 |
|-----------|----|
| uni_D − uni_T1 | long 3v D > baseline uni |
| best_late_D − best_late_T1 | melhor late D-grid > melhor late T1-grid |
| all_D − all_T1 | late all-D > late all-T1 |
| all_T1 − uni_T1 | multiclasse baseline > teto uni T1 |
| all_D − uni_D | multiclasse D > teto uni D |
| best_late_D − uni_D | melhor late D > teto uni D |
| volT1_shapeD − uni_T1 | âncora vol T1 ∪ forma D > teto uni T1 (= late âncora − vol T1 do v1) |


In [7]:
cfg = STATS_CFG


def _best_uni_mod(base: Path, protocol: str) -> str | None:
    best_mod, best_auc = None, -1.0
    for m in MODS_COMPARE:
        path = image_ablation_path(base, protocol, m)
        if not path.is_file():
            continue
        auc, _ = patient_auc(path, cfg_for_modality(m, cfg))
        if auc > best_auc:
            best_auc, best_mod = auc, m
    return best_mod


def _load_uni(base: Path, protocol: str, mod: str) -> pd.DataFrame:
    path = image_ablation_path(base, protocol, mod)
    return patient_scores_from_path(path, cfg_for_modality(mod, cfg))


def _load_late(base: Path, late_proto: str) -> pd.DataFrame:
    path = image_ablation_path(base, late_proto, late_proto)
    return patient_scores_from_path(
        path, cfg_for_modality(late_proto, cfg, protocol=late_proto)
    )


def _best_late_proto(base: Path, *, want_ols: bool) -> str | None:
    """Argmax AUC em late_fusion. T1-grid = sem t1_ols/d21; D-grid = com t1_ols."""
    root = base / "ablation_results_late_fusion"
    if not root.is_dir():
        return None
    best_proto, best_auc = None, -1.0
    for d in sorted(root.iterdir()):
        if not d.is_dir():
            continue
        fp = d.name
        has_ols = "t1_ols" in fp
        has_legacy = "d21" in fp  # specs B0 (Δ abs) ainda no disco: excluídas
        if want_ols:
            if not has_ols:
                continue
        else:
            if has_ols or has_legacy:
                continue
        proto = f"late__{fp}"
        path = d / "ablation_results_all.csv"
        if not path.is_file():
            continue
        try:
            auc, _ = patient_auc(path, cfg_for_modality(proto, cfg, protocol=proto))
        except Exception as e:
            print("skip late", fp, e)
            continue
        if auc > best_auc:
            best_auc, best_proto = auc, proto
    return best_proto


mod_t1 = _best_uni_mod(BASE, PROTOCOL_BASELINE)
mod_d = _best_uni_mod(BASE, PROTOCOL_LONGITUDINAL)
late_best_t1 = _best_late_proto(BASE, want_ols=False)
late_best_d = _best_late_proto(BASE, want_ols=True)
print(
    f"uni_T1 best={mod_t1} | uni_D best={mod_d}\n"
    f"best_late_T1={late_best_t1} | best_late_D={late_best_d}"
)

scores = {}
if mod_t1:
    scores["uni_T1"] = _load_uni(BASE, PROTOCOL_BASELINE, mod_t1)
if mod_d:
    scores["uni_D"] = _load_uni(BASE, PROTOCOL_LONGITUDINAL, mod_d)

for key, proto in (
    ("all_T1", LATE_ALL_T1),
    ("all_D", LATE_ALL_OLS),
    ("volT1_shapeD", LATE_VOL_T1_SHAPE_D),
):
    try:
        path = image_ablation_path(BASE, proto, proto)
    except KeyError:
        path = None
    if path is not None and path.is_file():
        scores[key] = _load_late(BASE, proto)
    else:
        print("MISSING late", proto, "→", path)

if late_best_t1:
    scores["best_late_T1"] = _load_late(BASE, late_best_t1)
if late_best_d:
    scores["best_late_D"] = _load_late(BASE, late_best_d)

# (name, a, b)  Δ = a − b; H1: a > b
CONTRASTS = [
    ("uni_D_minus_uni_T1", "uni_D", "uni_T1"),
    ("best_late_D_minus_best_late_T1", "best_late_D", "best_late_T1"),
    ("all_D_minus_all_T1", "all_D", "all_T1"),
    ("all_T1_minus_uni_T1", "all_T1", "uni_T1"),
    ("all_D_minus_uni_D", "all_D", "uni_D"),
    ("best_late_D_minus_uni_D", "best_late_D", "uni_D"),
    ("volT1_shapeD_minus_uni_T1", "volT1_shapeD", "uni_T1"),
]

rows = []
for i, (name, ka, kb) in enumerate(CONTRASTS):
    if ka not in scores or kb not in scores:
        print("skip", name, "(missing", ka if ka not in scores else kb, ")")
        continue
    paired = scores[ka].merge(
        scores[kb], on=["ID_PT", "y"], suffixes=("_a", "_b")
    )
    if paired.empty:
        print("sem pares", name)
        continue
    row = paired_comparison_row(
        paired,
        score_a="score_a",
        score_b="score_b",
        label_a="a",
        label_b="b",
        n_boot=cfg.n_bootstrap,
        seed=cfg.seed + 500 + i,
        permutation_auc_p=permutation_auc_p,
        n_perm=cfg.n_perm,
        alpha=ALPHA,
    )
    row.update({
        "contrast": name,
        "modality": name,
        "arm_a": ka,
        "arm_b": kb,
        "mod_uni_T1": mod_t1,
        "mod_uni_D": mod_d,
        "proto_best_late_T1": late_best_t1,
        "proto_best_late_D": late_best_d,
    })
    rows.append(row)

cmp_ceil = pd.DataFrame(rows)
if not cmp_ceil.empty:
    cmp_ceil["p_fdr_bh"] = apply_bh_fdr(cmp_ceil["p_bootstrap_one_sided"].to_numpy())
    cmp_ceil["significant_fdr"] = (cmp_ceil["p_fdr_bh"] < ALPHA) & (cmp_ceil["ci95_lo"] > 0)
    save_table(cmp_ceil, "stats_four_ceilings_48m6m")
    display(cmp_ceil.round(4))
    print("\n── ΔAUC tetos (a − b); FDR ──")
    print_comparison_summary(cmp_ceil, label_a="a", label_b="b")
else:
    print("four_ceilings: sem contrastes (falta mono/late no disco?)")


uni_T1 best=vol | uni_D best=vol
best_late_T1=late__t1_vol__t1_shape__t1_firstorder | best_late_D=late__t1_ols_vol__t1_ols_firstorder
Salvo: Artigo 1 pgirardi/tables/stats_four_ceilings_48m6m.csv


,n_pacientes,auc_a,auc_b,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,a_superior,p_perm_a,...,significant_raw,contrast,modality,arm_a,arm_b,mod_uni_T1,mod_uni_D,proto_best_late_T1,proto_best_late_D,p_fdr_bh
0,193,0.7838,0.7559,0.0279,-0.0130,0.0679,0.0916,0.1832,False,0.0002,...,False,uni_D_minus_uni_T1,uni_D_minus_uni_T1,uni_D,uni_T1,vol,vol,late__t1_vol__t1_shape__t1_firstorder,late__t1_ols_vol__t1_ols_firstorder,0.2137
1,193,0.8064,0.7734,0.0330,-0.0044,0.0724,0.0444,0.0888,False,0.0002,...,False,best_late_D_minus_best_late_T1,best_late_D_minus_best_late_T1,best_late_D,best_late_T1,vol,vol,late__t1_vol__t1_shape__t1_firstorder,late__t1_ols_vol__t1_ols_firstorder,0.1554
2,193,0.7908,0.7660,0.0248,-0.0002,0.0511,0.0266,0.0532,False,0.0002,...,False,all_D_minus_all_T1,all_D_minus_all_T1,all_D,all_T1,vol,vol,late__t1_vol__t1_shape__t1_firstorder,late__t1_ols_vol__t1_ols_firstorder,0.1554
3,193,0.7660,0.7559,0.0100,-0.0296,0.0518,0.3135,0.6271,False,0.0002,...,False,all_T1_minus_uni_T1,all_T1_minus_uni_T1,all_T1,uni_T1,vol,vol,late__t1_vol__t1_shape__t1_firstorder,late__t1_ols_vol__t1_ols_firstorder,0.3643
4,193,0.7908,0.7838,0.0070,-0.0334,0.0487,0.3643,0.7287,False,0.0002,...,False,all_D_minus_uni_D,all_D_minus_uni_D,all_D,uni_D,vol,vol,late__t1_vol__t1_shape__t1_firstorder,late__t1_ols_vol__t1_ols_firstorder,0.3643
5,193,0.8064,0.7838,0.0226,-0.0193,0.0644,0.1436,0.2871,False,0.0002,...,False,best_late_D_minus_uni_D,best_late_D_minus_uni_D,best_late_D,uni_D,vol,vol,late__t1_vol__t1_shape__t1_firstorder,late__t1_ols_vol__t1_ols_firstorder,0.2512
6,193,0.7627,0.7559,0.0067,-0.0259,0.0383,0.3461,0.6923,False,0.0002,...,False,volT1_shapeD_minus_uni_T1,volT1_shapeD_minus_uni_T1,volT1_shapeD,uni_T1,vol,vol,late__t1_vol__t1_shape__t1_firstorder,late__t1_ols_vol__t1_ols_firstorder,0.3643



── ΔAUC tetos (a − b); FDR ──
  uni_D_minus_uni_T1: ΔAUC=0.028 [-0.013, 0.068]  p=0.0916  q=0.2137  → sem evidência
  best_late_D_minus_best_late_T1: ΔAUC=0.033 [-0.004, 0.072]  p=0.0444  q=0.1554  → sem evidência
  all_D_minus_all_T1: ΔAUC=0.025 [-0.000, 0.051]  p=0.0266  q=0.1554  → sem evidência
  all_T1_minus_uni_T1: ΔAUC=0.010 [-0.030, 0.052]  p=0.3135  q=0.3643  → sem evidência
  all_D_minus_uni_D: ΔAUC=0.007 [-0.033, 0.049]  p=0.3643  q=0.3643  → sem evidência
  best_late_D_minus_uni_D: ΔAUC=0.023 [-0.019, 0.064]  p=0.1436  q=0.2512  → sem evidência
  volT1_shapeD_minus_uni_T1: ΔAUC=0.007 [-0.026, 0.038]  p=0.3461  q=0.3643  → sem evidência


## 6. Clínico vs vol T1 (`48m_6m`)

Imagem = **vol** `t1_only`. Fusão = clinic + vol T1.
Δ chave = (clinic+img) − clinic (IC bootstrap).


In [8]:
cfg = STATS_CFG
mod = CLINIC_MODALITY
img_cfg = cfg_for_modality(mod, cfg)
clin_cfg = cfg_clinical(cfg)
fusion_path = fusion_results_path(
    BASE, mod, selection_mode=cfg.selection_mode, with_combat=cfg.with_combat,
    representation="t1_only",
)
clin_path = clinical_results_path(BASE)
img_path = image_ablation_path(BASE, PROTOCOL_BASELINE, mod)

clinical_rows = []
pairs = [
    (img_path, clin_path, img_cfg, clin_cfg, "score_img", "score_clin", "img", "clin", "vol_t1_vs_clinical"),
    (fusion_path, clin_path, img_cfg, clin_cfg, "score_fusion", "score_clin", "fusion", "clin", "fusion_vs_clinical"),
    (fusion_path, img_path, img_cfg, img_cfg, "score_fusion", "score_img", "fusion", "img", "fusion_vs_vol_t1"),
]
for i, (pa, pb, ca, cb, sa, sb, la, lb, tag) in enumerate(pairs):
    if not pa.exists() or not pb.exists():
        print("MISSING", pa if not pa.exists() else pb)
        continue
    paired = patient_scores_from_path(pa, ca).merge(
        patient_scores_from_path(pb, cb), on=["ID_PT", "y"], suffixes=(f"_{la}", f"_{lb}"),
    )
    # suffixes only apply when column names collide; scores both named "score"
    if f"score_{la}" not in paired.columns:
        paired = patient_scores_from_path(pa, ca).rename(columns={"score": sa}).merge(
            patient_scores_from_path(pb, cb).rename(columns={"score": sb}),
            on=["ID_PT", "y"],
        )
    row = paired_comparison_row(
        paired, score_a=sa, score_b=sb, label_a=la, label_b=lb,
        n_boot=cfg.n_bootstrap, seed=cfg.seed + 200 + i,
        permutation_auc_p=permutation_auc_p, n_perm=cfg.n_perm, alpha=ALPHA,
    )
    row.update({"modality": mod, "comparison": tag})
    clinical_rows.append(row)

cmp_clinical = pd.DataFrame(clinical_rows)
if not cmp_clinical.empty:
    cmp_clinical["p_fdr_bh"] = apply_bh_fdr(cmp_clinical["p_bootstrap_one_sided"].to_numpy())
    cmp_clinical["significant_fdr"] = (
        (cmp_clinical["p_fdr_bh"] < ALPHA) & (cmp_clinical["ci95_lo"] > 0)
    )
    save_table(cmp_clinical, "stats_clinic_48m6m")
    display(cmp_clinical.round(4))
    for _, r in cmp_clinical.iterrows():
        print(
            f"  {r['comparison']}: Δ={r['delta_auc']:.3f} "
            f"[{r['ci95_lo']:.3f}, {r['ci95_hi']:.3f}]  p={r['p_bootstrap_one_sided']:.4f}"
        )


Salvo: Artigo 1 pgirardi/tables/stats_clinic_48m6m.csv


,n_pacientes,auc_img,auc_clin,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,img_superior,p_perm_img,p_perm_clin,significant_fdr,significant_raw,modality,comparison,auc_fusion,fusion_superior,p_perm_fusion,p_fdr_bh
0,193,0.7559,0.8396,-0.0837,-0.1650,-0.0035,0.9814,0.0372,False,0.0002,0.0002,False,False,vol,vol_t1_vs_clinical,NaN,NaN,NaN,0.9814
1,193,NaN,0.8396,0.0263,-0.0124,0.0640,0.0896,0.1792,NaN,NaN,0.0002,False,False,vol,fusion_vs_clinical,0.8659,False,0.0002,0.1344
2,193,0.7559,NaN,0.1099,0.0548,0.1652,0.0002,0.0004,NaN,0.0002,NaN,True,True,vol,fusion_vs_vol_t1,0.8659,True,0.0002,0.0006


  vol_t1_vs_clinical: Δ=-0.084 [-0.165, -0.004]  p=0.9814
  fusion_vs_clinical: Δ=0.026 [-0.012, 0.064]  p=0.0896
  fusion_vs_vol_t1: Δ=0.110 [0.055, 0.165]  p=0.0002


## 7. Soft True vs False (descritivo)

Pastas: `48m_6m` (120 pMCI) vs `48m_6m_soft_False` (74 pMCI).
SVM · T1 e D (OLS) · 5 famílias. **Sem** bootstrap pareado (n ≠; pacientes diferentes).
Δ = AUC(soft True) − AUC(soft False).


In [9]:
cfg = STATS_CFG
base_soft = Path(f"csvs/cohorts/{SOFT_FALSE_COHORT}")
rows_soft = []
for proto, lab in (
    (PROTOCOL_BASELINE, "t1_only"),
    (PROTOCOL_LONGITUDINAL, "t1_ols"),
):
    for mod in MODS_COMPARE:
        cfg_m = cfg_for_modality(mod, cfg)
        p_true = image_ablation_path(BASE, proto, mod)
        p_false = image_ablation_path(base_soft, proto, mod)
        if not p_true.is_file() or not p_false.is_file():
            print("MISSING", proto, mod, p_true.is_file(), p_false.is_file())
            continue
        auc_t, n_t = patient_auc(p_true, cfg_m)
        auc_f, n_f = patient_auc(p_false, cfg_m)
        rows_soft.append({
            "protocol": lab,
            "modality": mod,
            "auc_soft_true": auc_t,
            "n_soft_true": n_t,
            "auc_soft_false": auc_f,
            "n_soft_false": n_f,
            "delta_true_minus_false": auc_t - auc_f,
        })

cmp_soft = pd.DataFrame(rows_soft)
if not cmp_soft.empty:
    save_table(cmp_soft, "stats_soft_true_vs_false")
    display(cmp_soft.round(4))
    print("\n── pivot Δ (True−False) ──")
    display(
        cmp_soft.pivot(index="modality", columns="protocol", values="delta_true_minus_false")
        .reindex(index=list(MODS_COMPARE))
        .round(3)
    )


Salvo: Artigo 1 pgirardi/tables/stats_soft_true_vs_false.csv


,protocol,modality,auc_soft_true,n_soft_true,auc_soft_false,n_soft_false,delta_true_minus_false
0,t1_only,vol,0.7559,193,0.7381,147,0.0179
1,t1_only,shape,0.7115,193,0.7066,147,0.0049
2,t1_only,texture,0.6276,193,0.6261,147,0.0016
3,t1_only,disp,0.5404,193,0.4619,147,0.0785
4,t1_only,firstorder,0.6865,193,0.6973,147,-0.0108
5,t1_ols,vol,0.7838,193,0.7320,147,0.0518
6,t1_ols,shape,0.7282,193,0.7047,147,0.0235
7,t1_ols,texture,0.6080,193,0.5846,147,0.0234
8,t1_ols,disp,0.5732,193,0.4833,147,0.0898
9,t1_ols,firstorder,0.6918,193,0.6877,147,0.0041



── pivot Δ (True−False) ──


protocol,t1_ols,t1_only
modality,,
vol,0.052,0.018
shape,0.023,0.005
texture,0.023,0.002
disp,0.090,0.079
firstorder,0.004,-0.011


## 8. ComBat (sensibilidade, claim)

T1 harmonizado com NeuroComBat transversal (`ablation_results_combat_t1_only`); D harmonizado com ComBat longitudinal Beer 2020 (`ablation_results_ols_longcombat`). Ambos ajustados só no treino de cada fold.
Pareado por paciente em `48m_6m` · 5 famílias · SVM. Δ = a − b; H1 a > b; BH dentro de cada contraste (5 famílias).

| contraste (`protocol`) | a | b |
|---|---|---|
| `t1_neurocombat − t1` | T1 NeuroComBat | T1 nocombat |
| `ols_longcombat − ols` | D longComBat | D nocombat |
| `ols_longcombat − t1_neurocombat` | D longComBat | T1 NeuroComBat |


In [10]:
cfg = STATS_CFG
COMBAT_CONTRASTS = (
    # (protocol, path_a, with_combat_a, path_b, with_combat_b)   Δ = a − b
    ("t1_neurocombat − t1",
     lambda m: combat_ablation_path(BASE, PROTOCOL_BASELINE, m), True,
     lambda m: image_ablation_path(BASE, PROTOCOL_BASELINE, m), False),
    ("ols_longcombat − ols",
     lambda m: image_ablation_path(BASE, "t1_ols_longcombat", m), True,
     lambda m: image_ablation_path(BASE, PROTOCOL_LONGITUDINAL, m), False),
    ("ols_longcombat − t1_neurocombat",
     lambda m: image_ablation_path(BASE, "t1_ols_longcombat", m), True,
     lambda m: combat_ablation_path(BASE, PROTOCOL_BASELINE, m), True),
)
rows_c = []
for i, (lab, path_a, comb_a, path_b, comb_b) in enumerate(COMBAT_CONTRASTS):
    for j, mod in enumerate(MODS_COMPARE):
        p_a, p_b = path_a(mod), path_b(mod)
        if not p_a.is_file() or not p_b.is_file():
            print("MISSING", lab, mod)
            continue
        paired = patient_scores_from_path(p_a, cfg_for_modality(mod, cfg, with_combat=comb_a)).rename(
            columns={"score": "score_a"},
        ).merge(
            patient_scores_from_path(p_b, cfg_for_modality(mod, cfg, with_combat=comb_b)).rename(
                columns={"score": "score_b"},
            ),
            on=["ID_PT", "y"],
        )
        if paired.empty:
            print("sem pares", lab, mod)
            continue
        row = paired_comparison_row(
            paired,
            score_a="score_a",
            score_b="score_b",
            label_a="a",
            label_b="b",
            n_boot=cfg.n_bootstrap,
            seed=cfg.seed + 700 + 10 * i + j,
            permutation_auc_p=permutation_auc_p,
            n_perm=cfg.n_perm,
            alpha=ALPHA,
        )
        row.update({"protocol": lab, "modality": mod})
        rows_c.append(row)

cmp_combat = pd.DataFrame(rows_c)
if not cmp_combat.empty:
    # FDR dentro de cada protocol (5 fam)
    cmp_combat["p_fdr_bh"] = np.nan
    for lab, idx in cmp_combat.groupby("protocol").groups.items():
        q = apply_bh_fdr(cmp_combat.loc[idx, "p_bootstrap_one_sided"].to_numpy())
        cmp_combat.loc[idx, "p_fdr_bh"] = q
    cmp_combat["significant_fdr"] = (cmp_combat["p_fdr_bh"] < ALPHA) & (cmp_combat["ci95_lo"] > 0)
    save_table(cmp_combat, "stats_combat_vs_nocombat")
    display(cmp_combat.round(4))
    for lab, g in cmp_combat.groupby("protocol", sort=False):
        print(f"── ΔAUC = {lab} ──")
        print_comparison_summary(g, label_a="a", label_b="b")


Salvo: Artigo 1 pgirardi/tables/stats_combat_vs_nocombat.csv


,n_pacientes,auc_a,auc_b,delta_auc,ci95_lo,ci95_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,a_superior,p_perm_a,p_perm_b,significant_fdr,significant_raw,protocol,modality,p_fdr_bh
0,193,0.7376,0.7559,-0.0184,-0.0540,0.0173,0.8474,0.3051,False,0.0002,0.0002,False,False,t1_neurocombat − t1,vol,0.8474
1,193,0.7261,0.7115,0.0146,-0.0123,0.0427,0.1484,0.2967,False,0.0002,0.0002,False,False,t1_neurocombat − t1,shape,0.3709
2,193,0.6672,0.6276,0.0396,-0.0111,0.0896,0.0590,0.1180,False,0.0004,0.0012,False,False,t1_neurocombat − t1,texture,0.2949
3,193,0.5291,0.5404,-0.0113,-0.1212,0.1001,0.5771,0.8458,False,0.2438,0.1766,False,False,t1_neurocombat − t1,disp,0.8474
4,193,0.6705,0.6865,-0.0160,-0.0776,0.0436,0.7017,0.5967,False,0.0002,0.0002,False,False,t1_neurocombat − t1,firstorder,0.8474
5,193,0.7412,0.7838,-0.0426,-0.0782,-0.0107,0.9970,0.0060,False,0.0002,0.0002,False,False,ols_longcombat − ols,vol,0.9970
6,193,0.7282,0.7282,-0.0000,-0.0290,0.0299,0.5055,0.9890,False,0.0002,0.0002,False,False,ols_longcombat − ols,shape,0.9970
7,193,0.6636,0.6080,0.0556,0.0098,0.1003,0.0080,0.0160,True,0.0004,0.0048,True,True,ols_longcombat − ols,texture,0.0400
8,193,0.4869,0.5732,-0.0863,-0.1592,-0.0124,0.9900,0.0200,False,0.6217,0.0394,False,False,ols_longcombat − ols,disp,0.9970
9,193,0.6672,0.6918,-0.0245,-0.0852,0.0372,0.7768,0.4463,False,0.0002,0.0002,False,False,ols_longcombat − ols,firstorder,0.9970


── ΔAUC = t1_neurocombat − t1 ──
  vol: ΔAUC=-0.018 [-0.054, 0.017]  p=0.8474  q=0.8474  → sem evidência
  shape: ΔAUC=0.015 [-0.012, 0.043]  p=0.1484  q=0.3709  → sem evidência
  texture: ΔAUC=0.040 [-0.011, 0.090]  p=0.0590  q=0.2949  → sem evidência
  disp: ΔAUC=-0.011 [-0.121, 0.100]  p=0.5771  q=0.8474  → sem evidência
  firstorder: ΔAUC=-0.016 [-0.078, 0.044]  p=0.7017  q=0.8474  → sem evidência
── ΔAUC = ols_longcombat − ols ──
  vol: ΔAUC=-0.043 [-0.078, -0.011]  p=0.9970  q=0.9970  → sem evidência
  shape: ΔAUC=-0.000 [-0.029, 0.030]  p=0.5055  q=0.9970  → sem evidência
  texture: ΔAUC=0.056 [0.010, 0.100]  p=0.0080  q=0.0400  → FDR sig.
  disp: ΔAUC=-0.086 [-0.159, -0.012]  p=0.9900  q=0.9970  → sem evidência
  firstorder: ΔAUC=-0.025 [-0.085, 0.037]  p=0.7768  q=0.9970  → sem evidência
── ΔAUC = ols_longcombat − t1_neurocombat ──
  vol: ΔAUC=0.004 [-0.042, 0.051]  p=0.4395  q=0.7439  → sem evidência
  shape: ΔAUC=0.002 [-0.045, 0.049]  p=0.4631  q=0.7439  → sem evidência
  t

## 9. Tabela D — resumo complementares (claim)

Uma linha por análise: clinic, clinic+vol, ComBat (T1), soft (T1/D).


In [11]:
rows_d = []

def _add(analysis, detail, auc=None, delta=None, note=""):
    rows_d.append({
        "analysis": analysis,
        "detail": detail,
        "auc": auc,
        "delta": delta,
        "note": note,
    })

# clinic
if "cmp_clinical" in dir() and not cmp_clinical.empty:
    for tag in ("vol_t1_vs_clinical", "fusion_vs_clinical", "fusion_vs_vol_t1"):
        sub = cmp_clinical.loc[cmp_clinical["comparison"] == tag]
        if sub.empty:
            continue
        r = sub.iloc[0]
        _add("clinic", tag, auc=None, delta=r.get("delta_auc"),
             note=f"[{r['ci95_lo']:.3f},{r['ci95_hi']:.3f}]")

# combat mean |Δ| by protocol (descriptive row)
if "cmp_combat" in dir() and not cmp_combat.empty:
    for lab, g in cmp_combat.groupby("protocol"):
        _add("combat_vs_nocombat", lab,
             auc=None,
             delta=float(g["delta_auc"].mean()),
             note=f"mean ΔAUC over 5 fam; n_sig_fdr={int(g['significant_fdr'].sum())}")

# soft mean Δ
if "cmp_soft" in dir() and not cmp_soft.empty:
    for lab, g in cmp_soft.groupby("protocol"):
        _add("soft_true_vs_false", lab,
             auc=None,
             delta=float(g["delta_true_minus_false"].mean()),
             note="descriptive mean Δ over 5 fam; n_pMCI 120 vs 74")

table_d = pd.DataFrame(rows_d)
save_table(table_d, "stats_table_d_complements")
display(table_d.round(4))


Salvo: Artigo 1 pgirardi/tables/stats_table_d_complements.csv


,analysis,detail,auc,delta,note
0,clinic,vol_t1_vs_clinical,None,-0.0837,"[-0.165,-0.004]"
1,clinic,fusion_vs_clinical,None,0.0263,"[-0.012,0.064]"
2,clinic,fusion_vs_vol_t1,None,0.1099,"[0.055,0.165]"
3,combat_vs_nocombat,ols_longcombat − ols,None,-0.0196,mean ΔAUC over 5 fam; n_sig_fdr=1
4,combat_vs_nocombat,ols_longcombat − t1_neurocombat,None,-0.0087,mean ΔAUC over 5 fam; n_sig_fdr=0
5,combat_vs_nocombat,t1_neurocombat − t1,None,0.0017,mean ΔAUC over 5 fam; n_sig_fdr=0
6,soft_true_vs_false,t1_ols,None,0.0385,descriptive mean Δ over 5 fam; n_pMCI 120 vs 74
7,soft_true_vs_false,t1_only,None,0.0184,descriptive mean Δ over 5 fam; n_pMCI 120 vs 74


## 10. Sensibilidade α = 1% (uni 5 famílias × 4 coortes + tetos late fusion)

Requer §4 e §5 executados. Bootstrap refeito com **mesmas seeds** (mesmas reamostras → mesmo p) só para obter IC 99%, e só onde p < 5% (resto `ci99` = NaN: nunca passa a 1%).

Critérios (IC do nível α precisa excluir 0):
- `sig_raw_*`: p unilateral < α, sem correção.
- `sig_fdr_coorte_*`: q BH dentro da coorte (5 famílias) — critério atual do §4. Tetos: q sobre os 7 contrastes.
- `sig_fdr_global_*`: q BH sobre as 20 (4 coortes × 5 famílias) de cada contraste. Tetos: igual ao anterior.

Saída: `stats_sensitivity_alpha01`.

In [12]:
import importlib

import stats_compare

importlib.reload(stats_compare)  # kernel pode ter versão sem ci_level
from stats_compare import bootstrap_auc_diff_test

ALPHA_SENS = 0.01
cfg = STATS_CFG


def _ci(paired: pd.DataFrame, seed: int, p_ref: float) -> tuple[float, float]:
    _, lo, hi, p1, _ = bootstrap_auc_diff_test(
        paired["y"], paired["score_a"], paired["score_b"],
        n_boot=cfg.n_bootstrap, seed=seed, ci_level=1 - ALPHA_SENS,
    )
    assert abs(p1 - p_ref) < 1e-12, f"bootstrap não reproduziu p ({p1} vs {p_ref}): seed/pares mudaram"
    return lo, hi


parts = []
for name in ("cmp_gradient_ols", "cmp_gradient_r10", "cmp_gradient_r10r21"):
    g = globals().get(name)
    if g is None or g.empty:
        print("SKIP", name, "(rode §4)")
        continue
    g = g.copy()
    proto = g["contrast"].iloc[0].removesuffix("_vs_t1_only")
    g["p_fdr_global"] = apply_bh_fdr(g["p_bootstrap_one_sided"].to_numpy())
    ci = []
    for _, r in g.iterrows():
        if r["p_bootstrap_one_sided"] >= ALPHA:  # ponytail: ~30 s/bootstrap; p ≥ 5% nunca passa a 1%
            ci.append((np.nan, np.nan))
            continue
        base, mod = Path(f"csvs/cohorts/{r['cohort']}"), r["modality"]
        c = cfg_for_modality(mod, cfg)
        paired = patient_scores_from_path(image_ablation_path(base, proto, mod), c).merge(
            patient_scores_from_path(image_ablation_path(base, PROTOCOL_BASELINE, mod), c),
            on=["ID_PT", "y"], suffixes=("_a", "_b"),
        )
        # seed = compare_modalities: seed + i*17, bootstrap +2
        seed = cfg.seed + MODS_COMPARE.index(mod) * 17 + 2
        ci.append(_ci(paired, seed, r["p_bootstrap_one_sided"]))
    g["ci99_lo"], g["ci99_hi"] = zip(*ci)
    g["scope"] = "uni_5fam_x_4coortes"
    parts.append(g)

if "cmp_ceil" in dir() and not cmp_ceil.empty:
    g = cmp_ceil.copy()
    g["cohort"] = COHORT_CLAIM
    g["p_fdr_global"] = g["p_fdr_bh"]  # lista pré-spec já é a família inteira
    idx = {n: i for i, (n, _, _) in enumerate(CONTRASTS)}
    ci = []
    for _, r in g.iterrows():
        if r["p_bootstrap_one_sided"] >= ALPHA:
            ci.append((np.nan, np.nan))
            continue
        paired = scores[r["arm_a"]].merge(
            scores[r["arm_b"]], on=["ID_PT", "y"], suffixes=("_a", "_b")
        )
        # seed = §5: seed + 500 + i, bootstrap +2
        ci.append(_ci(paired, cfg.seed + 500 + idx[r["contrast"]] + 2, r["p_bootstrap_one_sided"]))
    g["ci99_lo"], g["ci99_hi"] = zip(*ci)
    g["scope"] = "late_fusion_tetos_48m6m"
    parts.append(g)
else:
    print("SKIP tetos (rode §5)")

sens = pd.concat(parts, ignore_index=True)
p1 = sens["p_bootstrap_one_sided"]
sens["p_bootstrap_two_sided"] = 2 * np.minimum(p1, 1 - p1)
flags = []
for a, lo_col in ((ALPHA, "ci95_lo"), (ALPHA_SENS, "ci99_lo")):
    tag, ci_ok = f"{round(a * 100)}pct", sens[lo_col] > 0
    for crit, p_col in (("raw", "p_bootstrap_one_sided"), ("fdr_coorte", "p_fdr_bh"), ("fdr_global", "p_fdr_global")):
        sens[f"sig_{crit}_{tag}"] = (sens[p_col] < a) & ci_ok
        flags.append(f"sig_{crit}_{tag}")

# ponytail: sanity — q ≥ p e IC 99% contém IC 95%
assert (sens["p_fdr_global"] >= p1 - 1e-12).all()
has99 = sens["ci99_lo"].notna()
assert ((sens["ci99_lo"] <= sens["ci95_lo"] + 1e-12) & (sens["ci99_hi"] >= sens["ci95_hi"] - 1e-12))[has99].all()

cols_s = [
    "scope", "contrast", "cohort", "modality", "n_pacientes", "delta_auc",
    "ci95_lo", "ci95_hi", "ci99_lo", "ci99_hi",
    "p_bootstrap_one_sided", "p_bootstrap_two_sided", "p_fdr_bh", "p_fdr_global", *flags,
]
save_table(sens[cols_s], "stats_sensitivity_alpha01")

print("\n── nº de contrastes significativos por critério (5% vs 1%) ──")
display(sens.groupby(["scope", "contrast"])[flags].sum())

print("\n── contrastes com alguma evidência a 5% → sobrevivem a 1%? ──")
hits = sens.loc[sens[flags].any(axis=1), cols_s]
display(hits.round(4) if not hits.empty else "nenhum")

Salvo: Artigo 1 pgirardi/tables/stats_sensitivity_alpha01.csv

── nº de contrastes significativos por critério (5% vs 1%) ──


sig_raw_5pct  \
scope                   contrast                                       
late_fusion_tetos_48m6m all_D_minus_all_T1                         0   
                        all_D_minus_uni_D                          0   
                        all_T1_minus_uni_T1                        0   
                        best_late_D_minus_best_late_T1             0   
                        best_late_D_minus_uni_D                    0   
                        uni_D_minus_uni_T1                         0   
                        volT1_shapeD_minus_uni_T1                  0   
uni_5fam_x_4coortes     t1_ols_vs_t1_only                          2   
                        t1_r10_r21_vs_t1_only                      1   
                        t1_r10_vs_t1_only                          1   

                                                        sig_fdr_coorte_5pct  \
scope                   contrast                                              
late_fusion_tetos_48m6m all_D_minus_all_T1                                0   
                        all_D_minus_uni_D                                 0   
                        all_T1_minus_uni_T1                               0   
                        best_late_D_minus_best_late_T1                    0   
                        best_late_D_minus_uni_D                           0   
                        uni_D_minus_uni_T1                                0   
                        volT1_shapeD_minus_uni_T1                         0   
uni_5fam_x_4coortes     t1_ols_vs_t1_only                                 1   
                        t1_r10_r21_vs_t1_only                             0   
                        t1_r10_vs_t1_only                                 1   

                                                        sig_fdr_global_5pct  \
scope                   contrast                                              
late_fusion_tetos_48m6m all_D_minus_all_T1                                0   
                        all_D_minus_uni_D                                 0   
                        all_T1_minus_uni_T1                               0   
                        best_late_D_minus_best_late_T1                    0   
                        best_late_D_minus_uni_D                           0   
                        uni_D_minus_uni_T1                                0   
                        volT1_shapeD_minus_uni_T1                         0   
uni_5fam_x_4coortes     t1_ols_vs_t1_only                                 0   
                        t1_r10_r21_vs_t1_only                             0   
                        t1_r10_vs_t1_only                                 0   

                                                        sig_raw_1pct  \
scope                   contrast                                       
late_fusion_tetos_48m6m all_D_minus_all_T1                         0   
                        all_D_minus_uni_D                          0   
                        all_T1_minus_uni_T1                        0   
                        best_late_D_minus_best_late_T1             0   
                        best_late_D_minus_uni_D                    0   
                        uni_D_minus_uni_T1                         0   
                        volT1_shapeD_minus_uni_T1                  0   
uni_5fam_x_4coortes     t1_ols_vs_t1_only                          1   
                        t1_r10_r21_vs_t1_only                      0   
                        t1_r10_vs_t1_only                          0   

                                                        sig_fdr_coorte_1pct  \
scope                   contrast                                              
late_fusion_tetos_48m6m all_D_minus_all_T1                                0   
                        all_D_minus_uni_D                                 0   
                        all_T1_minus_uni_T1                               0   
                        best_late


── contrastes com alguma evidência a 5% → sobrevivem a 1%? ──


,scope,contrast,cohort,modality,n_pacientes,delta_auc,ci95_lo,ci95_hi,ci99_lo,ci99_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,p_fdr_bh,p_fdr_global,sig_raw_5pct,sig_fdr_coorte_5pct,sig_fdr_global_5pct,sig_raw_1pct,sig_fdr_coorte_1pct,sig_fdr_global_1pct
2,uni_5fam_x_4coortes,t1_ols_vs_t1_only,36m_6m,texture,231,0.0546,0.0047,0.1036,-0.0099,0.1185,0.0160,0.0320,0.080,0.1600,True,False,False,False,False,False
15,uni_5fam_x_4coortes,t1_ols_vs_t1_only,48m_12m,vol,120,0.1331,0.0397,0.2273,0.0070,0.2555,0.0040,0.0080,0.020,0.0800,True,True,False,True,False,False
22,uni_5fam_x_4coortes,t1_r10_vs_t1_only,36m_6m,texture,231,0.0762,0.0123,0.1428,-0.0037,0.1618,0.0090,0.0180,0.045,0.1800,True,True,False,False,False,False
55,uni_5fam_x_4coortes,t1_r10_r21_vs_t1_only,48m_12m,vol,120,0.0848,0.0044,0.1672,-0.0241,0.1914,0.0208,0.0416,0.104,0.3819,True,False,False,False,False,False


## 11. Escolha B / C / D (Friedman, suplemento)

D (`t1_ols`) escolhido *a priori* (3 visitas, robusto a ruído de 1 visita, nível + inclinação interpretáveis). Aqui só confirma/nega.

- Blocos: 5 famílias × 4 coortes = 20; tratamentos B=`t1_r10_r21`, C=`t1_rate02`, D=`t1_ols`; AUC paciente SVM (mesmos IDs por bloco).
- Friedman; se p < 0.05 → Wilcoxon pareado D−B, D−C com Holm (2 testes).
- Limitação: coortes compartilham pacientes → blocos não independentes; leitura descritiva.

Saída: `stats_friedman_bcd_blocks`, `stats_friedman_bcd_posthoc`.

In [13]:
from scipy.stats import friedmanchisquare, wilcoxon

ENC_BCD = {"B": PROTOCOL_LONG_B, "C": "t1_rate02", "D": PROTOCOL_LONGITUDINAL}
rows_f = []
for coh in COHORTS_GRADIENT:
    base = Path(f"csvs/cohorts/{coh}")
    for mod in MODS_COMPARE:
        r = {"cohort": coh, "modality": mod}
        for k, proto in ENC_BCD.items():
            r[k], r[f"n_{k}"] = patient_auc(image_ablation_path(base, proto, mod), cfg_for_modality(mod))
        rows_f.append(r)
blocks = pd.DataFrame(rows_f)
assert len(blocks) == 20, len(blocks)
assert (blocks[[f"n_{k}" for k in ENC_BCD]].nunique(axis=1) == 1).all(), "n difere entre B/C/D num bloco"

chi2_f, p_fried = friedmanchisquare(*(blocks[k] for k in ENC_BCD))
mean_rank = blocks[list(ENC_BCD)].rank(axis=1, ascending=False).mean()
print(f"Friedman χ²={chi2_f:.3f}  p={p_fried:.4f}  | rank médio (1=melhor):", mean_rank.round(2).to_dict())

post_f = pd.DataFrame([
    {
        "contrast": f"D−{o}",
        "median_delta": float((blocks["D"] - blocks[o]).median()),
        "mean_delta": float((blocks["D"] - blocks[o]).mean()),
        "n_D_better": int((blocks["D"] > blocks[o]).sum()),
        "p_wilcoxon": float(wilcoxon(blocks["D"], blocks[o]).pvalue),
    }
    for o in ("B", "C")
]).sort_values("p_wilcoxon", ignore_index=True)
post_f["p_holm"] = np.minimum(
    1, np.maximum.accumulate(post_f["p_wilcoxon"].to_numpy() * np.arange(len(post_f), 0, -1)),
)
post_f["friedman_chi2"] = chi2_f
post_f["friedman_p"] = p_fried
post_f["posthoc_valid"] = p_fried < ALPHA

# ponytail: sanity Holm — p_holm ≥ p e monótono na ordem dos p
assert (post_f["p_holm"] >= post_f["p_wilcoxon"]).all() and post_f["p_holm"].is_monotonic_increasing

save_table(blocks, "stats_friedman_bcd_blocks")
save_table(post_f, "stats_friedman_bcd_posthoc")
display(blocks.round(3))
display(post_f.round(4))

Friedman χ²=6.100  p=0.0474  | rank médio (1=melhor): {'B': 2.45, 'C': 1.8, 'D': 1.75}
Salvo: Artigo 1 pgirardi/tables/stats_friedman_bcd_blocks.csv
Salvo: Artigo 1 pgirardi/tables/stats_friedman_bcd_posthoc.csv


,cohort,modality,B,n_B,C,n_C,D,n_D
0,36m_6m,vol,0.771,231,0.794,231,0.790,231
1,36m_6m,shape,0.741,231,0.745,231,0.744,231
2,36m_6m,texture,0.679,231,0.665,231,0.673,231
3,36m_6m,disp,0.590,231,0.607,231,0.608,231
4,36m_6m,firstorder,0.667,231,0.664,231,0.666,231
5,36m_12m,vol,0.685,154,0.703,154,0.708,154
6,36m_12m,shape,0.726,154,0.716,154,0.716,154
7,36m_12m,texture,0.527,154,0.542,154,0.536,154
8,36m_12m,disp,0.357,154,0.389,154,0.389,154
9,36m_12m,firstorder,0.574,154,0.578,154,0.567,154


,contrast,median_delta,mean_delta,n_D_better,p_wilcoxon,p_holm,friedman_chi2,friedman_p,posthoc_valid
0,D−B,0.0095,0.0098,14,0.0240,0.0479,6.1,0.0474,True
1,D−C,0.0001,-0.0000,11,0.7795,0.7795,6.1,0.0474,True


## 12. União multiclasse (5 famílias) × 4 coortes — baseline vs D

Late fusion = média dos escores OOF das 5 SVMs uniclasse (Eq. late-mean). Como a média é linear, o escore do paciente = média dos 5 escores-paciente uniclasse → reproduz `late__*` do disco em `48m_6m` (all-T1 0.766, all-D 0.791) e all-T1 nas outras coortes, sem rerodar.

Contrastes por coorte (bootstrap pareado, H1 a > b): `all_D − all_T1`, `all_T1 − uni_T1`, `all_D − uni_D` (uni = argmax da coorte). BH sobre as 4 coortes de cada contraste (`p_fdr_bh`) e sobre os 12 (`p_fdr_global`); IC 99% só onde p < 5%.

Saída: `stats_union_4cohorts`.

In [14]:
from stats_compare import bootstrap_auc_diff_test

cfg = STATS_CFG
UNION_CONTRASTS = (
    ("all_D_minus_all_T1", "all_D", "all_T1"),
    ("all_T1_minus_uni_T1", "all_T1", "uni_T1"),
    ("all_D_minus_uni_D", "all_D", "uni_D"),
)


def _pat_scores(base: Path, proto: str) -> pd.DataFrame:
    """Escore-paciente por família (colunas = MODS_COMPARE)."""
    out = None
    for m in MODS_COMPARE:
        s = patient_scores_from_path(image_ablation_path(base, proto, m), cfg_for_modality(m, cfg))
        s = s.rename(columns={"score": m})
        out = s if out is None else out.merge(s, on=["ID_PT", "y"])
    return out


rows_u = []
for ci, coh in enumerate(COHORTS_GRADIENT):
    base = Path(f"csvs/cohorts/{coh}")
    arms = {}
    for tag, proto in (("T1", PROTOCOL_BASELINE), ("D", PROTOCOL_LONGITUDINAL)):
        s = _pat_scores(base, proto)
        best = max(MODS_COMPARE, key=lambda m: roc_auc_score(s["y"], s[m]))
        arms[f"all_{tag}"] = s.assign(score=s[list(MODS_COMPARE)].mean(axis=1))[["ID_PT", "y", "score"]]
        arms[f"uni_{tag}"] = s.assign(score=s[best])[["ID_PT", "y", "score"]]
        arms[f"best_{tag}"] = best
    for j, (name, ka, kb) in enumerate(UNION_CONTRASTS):
        paired = arms[ka].merge(arms[kb], on=["ID_PT", "y"], suffixes=("_a", "_b"))
        seed = cfg.seed + 900 + 10 * ci + j
        row = paired_comparison_row(
            paired, score_a="score_a", score_b="score_b", label_a="a", label_b="b",
            n_boot=cfg.n_bootstrap, seed=seed,
            permutation_auc_p=permutation_auc_p, n_perm=cfg.n_perm, alpha=ALPHA,
        )
        lo99 = hi99 = np.nan
        if row["p_bootstrap_one_sided"] < ALPHA:
            _, lo99, hi99, p1, _ = bootstrap_auc_diff_test(
                paired["y"], paired["score_a"], paired["score_b"],
                n_boot=cfg.n_bootstrap, seed=seed + 2, ci_level=0.99,
            )
            assert abs(p1 - row["p_bootstrap_one_sided"]) < 1e-12
        row.update({
            "cohort": coh, "contrast": name, "arm_a": ka, "arm_b": kb,
            "best_uni_T1": arms["best_T1"], "best_uni_D": arms["best_D"],
            "ci99_lo": lo99, "ci99_hi": hi99,
        })
        rows_u.append(row)

cmp_union = pd.DataFrame(rows_u)
cmp_union["p_fdr_bh"] = cmp_union.groupby("contrast")["p_bootstrap_one_sided"].transform(
    lambda p: apply_bh_fdr(p.to_numpy())
)
cmp_union["p_fdr_global"] = apply_bh_fdr(cmp_union["p_bootstrap_one_sided"].to_numpy())
for a, lo_col in ((ALPHA, "ci95_lo"), (0.01, "ci99_lo")):
    tag = f"{round(a * 100)}pct"
    for crit, p_col in (("raw", "p_bootstrap_one_sided"), ("fdr", "p_fdr_bh"), ("fdr_global", "p_fdr_global")):
        cmp_union[f"sig_{crit}_{tag}"] = (cmp_union[p_col] < a) & (cmp_union[lo_col] > 0)

# ponytail: sanity — reproduz late fusion do disco em 48m_6m (all-T1 0.766, all-D 0.791)
claim = cmp_union.query("cohort == @COHORT_CLAIM and contrast == 'all_D_minus_all_T1'").iloc[0]
assert abs(claim["auc_a"] - 0.7907) < 2e-3 and abs(claim["auc_b"] - 0.7659) < 2e-3, claim[["auc_a", "auc_b"]]

save_table(cmp_union, "stats_union_4cohorts")
cols_u = [
    "cohort", "contrast", "best_uni_T1", "best_uni_D", "auc_a", "auc_b", "delta_auc",
    "ci95_lo", "ci95_hi", "ci99_lo", "ci99_hi", "p_bootstrap_one_sided", "p_fdr_bh", "p_fdr_global",
    "sig_raw_5pct", "sig_fdr_5pct", "sig_raw_1pct", "sig_fdr_1pct",
]
display(cmp_union[cols_u].round(4))

Salvo: Artigo 1 pgirardi/tables/stats_union_4cohorts.csv


,cohort,contrast,best_uni_T1,best_uni_D,auc_a,auc_b,delta_auc,ci95_lo,ci95_hi,ci99_lo,ci99_hi,p_bootstrap_one_sided,p_fdr_bh,p_fdr_global,sig_raw_5pct,sig_fdr_5pct,sig_raw_1pct,sig_fdr_1pct
0,36m_6m,all_D_minus_all_T1,vol,vol,0.8046,0.7768,0.0278,0.0002,0.0558,-0.0080,0.0653,0.0248,0.0344,0.1032,True,True,False,False
1,36m_6m,all_T1_minus_uni_T1,vol,vol,0.7768,0.7656,0.0112,-0.0238,0.0455,NaN,NaN,0.2591,0.4196,0.4611,False,False,False,False
2,36m_6m,all_D_minus_uni_D,vol,vol,0.8046,0.7901,0.0145,-0.0183,0.0475,NaN,NaN,0.1956,0.3911,0.4611,False,False,False,False
3,36m_12m,all_D_minus_all_T1,vol,shape,0.6742,0.6724,0.0018,-0.0595,0.0617,NaN,NaN,0.4821,0.4821,0.5785,False,False,False,False
4,36m_12m,all_T1_minus_uni_T1,vol,shape,0.6724,0.6900,-0.0175,-0.1084,0.0747,NaN,NaN,0.6437,0.6437,0.7022,False,False,False,False
5,36m_12m,all_D_minus_uni_D,vol,shape,0.6742,0.7160,-0.0418,-0.1352,0.0516,NaN,NaN,0.8158,0.8158,0.8158,False,False,False,False
6,48m_6m,all_D_minus_all_T1,vol,vol,0.7908,0.7660,0.0248,-0.0003,0.0508,-0.0082,0.0612,0.0258,0.0344,0.1032,False,False,False,False
7,48m_6m,all_T1_minus_uni_T1,vol,vol,0.7660,0.7559,0.0100,-0.0310,0.0500,NaN,NaN,0.3147,0.4196,0.4721,False,False,False,False
8,48m_6m,all_D_minus_uni_D,vol,vol,0.7908,0.7838,0.0070,-0.0352,0.0468,NaN,NaN,0.3679,0.4906,0.4906,False,False,False,False
9,48m_12m,all_D_minus_all_T1,shape,vol,0.8021,0.7306,0.0715,0.0147,0.1327,-0.0017,0.1553,0.0066,0.0264,0.0792,True,True,False,False


## 13. IC 99% dos complementares significativos a 5%

Mesmas seeds dos §2, §6, §8 e §4 (soft False) → mesmo p; só muda o IC (99%). Critério 1%: p (ou q) < 0.01 **e** IC 99% > 0.

Saída: `stats_complement_alpha01`.

In [15]:
cfg = STATS_CFG


def _pair(path_a, cfg_a, path_b, cfg_b):
    return patient_scores_from_path(path_a, cfg_a).rename(columns={"score": "score_a"}).merge(
        patient_scores_from_path(path_b, cfg_b).rename(columns={"score": "score_b"}), on=["ID_PT", "y"],
    )


vol_t1 = (image_ablation_path(BASE, PROTOCOL_BASELINE, "vol"), cfg_for_modality("vol", cfg))
base_soft = Path(f"csvs/cohorts/{SOFT_FALSE_COHORT}")
cases = [  # (análise, pares, seed do bootstrap = seed da célula original + 2)
    *[(f"vol T1 − {lab}",
       _pair(*vol_t1, CLIN_DIR / f"clinical_{tag}_results_all.csv", cfg_clinical(cfg)),
       cfg.seed + 200 + 10 * k + 2)
      for k, (tag, lab) in enumerate(DEMO_TAGS.items())],
    ("(clínico + vol T1) − vol T1",
     _pair(fusion_path, img_cfg, *vol_t1), cfg.seed + 200 + 2 + 2),
    ("D longComBat − D (textura)",
     _pair(image_ablation_path(BASE, "t1_ols_longcombat", "texture"), cfg_for_modality("texture", cfg, with_combat=True),
           image_ablation_path(BASE, PROTOCOL_LONGITUDINAL, "texture"), cfg_for_modality("texture", cfg)),
     cfg.seed + 700 + 10 * 1 + 2 + 2),
    ("soft False: B − T1 (disp)",
     _pair(image_ablation_path(base_soft, PROTOCOL_LONG_B, "disp"), cfg_for_modality("disp", cfg),
           image_ablation_path(base_soft, PROTOCOL_BASELINE, "disp"), cfg_for_modality("disp", cfg)),
     cfg.seed + MODS_COMPARE.index("disp") * 17 + 2),
]
rows_99 = []
for name, paired, seed in cases:
    d, lo, hi, p1, _ = bootstrap_auc_diff_test(
        paired["y"], paired["score_a"], paired["score_b"], n_boot=cfg.n_bootstrap, seed=seed, ci_level=0.99,
    )
    rows_99.append({"analise": name, "delta_auc": d, "ci99_lo": lo, "ci99_hi": hi, "p_bootstrap_one_sided": p1,
                    "sig_raw_1pct": (p1 < 0.01) and (lo > 0)})
comp99 = pd.DataFrame(rows_99)
save_table(comp99, "stats_complement_alpha01")
display(comp99.round(4))

Salvo: Artigo 1 pgirardi/tables/stats_complement_alpha01.csv


,analise,delta_auc,ci99_lo,ci99_hi,p_bootstrap_one_sided,sig_raw_1pct
0,vol T1 − idade,0.3606,0.2019,0.5037,0.0002,True
1,vol T1 − sexo,0.2928,0.1376,0.4374,0.0002,True
2,vol T1 − idade+sexo,0.2137,0.0669,0.3611,0.0002,True
3,(clínico + vol T1) − vol T1,0.1099,0.0374,0.1826,0.0002,True
4,D longComBat − D (textura),0.0556,-0.0050,0.1141,0.0080,False
5,soft False: B − T1 (disp),0.0700,-0.0064,0.1443,0.0088,False


## 14. Complementares extras (`48m_6m`): vol ∪ idade+sexo e template AD do deslocamento

Requer só §1–§2 (setup). Bootstrap pareado + permutação, IC 95% e IC 99% (mesma seed → mesmo p). BH dentro de cada família.

| família | a | b | pergunta |
|---|---|---|---|
| `fusao_demo` | vol ∪ idade+sexo | vol T1 | idade+sexo acrescentam ao volume? |
| `fusao_demo` | vol ∪ idade+sexo | idade+sexo | volume acrescenta à demografia? |
| `fusao_demo` | vol ∪ clínico | vol ∪ idade+sexo | MMSE/ADAS/FAQ acrescentam a vol+demografia? |
| `disp_template` | disp AD | disp CN | template AD > template CN (baseline)? |
| `disp_template` | disp CN+AD | disp CN | concatenar os dois referenciais ajuda? |

Saída: `stats_complement_extra_48m6m`.

In [16]:
from stats_compare import bootstrap_auc_diff_test

cfg = STATS_CFG
CLIN_DIR = BASE / "ablation_results_clinic"
vol_cfg = cfg_for_modality("vol", cfg)
fus_clin = fusion_results_path(
    BASE, "vol", selection_mode=cfg.selection_mode, with_combat=cfg.with_combat, representation="t1_only",
)
fus_demo = fus_clin.with_name(fus_clin.name.replace("_results_all", "_sex_age_results_all"))
arms_x = {
    "vol T1": (image_ablation_path(BASE, PROTOCOL_BASELINE, "vol"), vol_cfg),
    "idade+sexo": (CLIN_DIR / "clinical_sex_age_results_all.csv", cfg_clinical(cfg)),
    "vol ∪ idade+sexo": (fus_demo, vol_cfg),
    "vol ∪ clínico": (fus_clin, vol_cfg),
    "disp CN": (image_ablation_path(BASE, PROTOCOL_BASELINE, "disp"), cfg_for_modality("disp", cfg)),
    "disp AD": (image_ablation_path(BASE, PROTOCOL_BASELINE, "disp_ad"), cfg_for_modality("disp_ad", cfg)),
    "disp CN+AD": (image_ablation_path(BASE, PROTOCOL_BASELINE, "disp_cnad"), cfg_for_modality("disp_cnad", cfg)),
}
EXTRA = [  # (família BH, a, b)   Δ = a − b; H1: a > b
    ("fusao_demo", "vol ∪ idade+sexo", "vol T1"),
    ("fusao_demo", "vol ∪ idade+sexo", "idade+sexo"),
    ("fusao_demo", "vol ∪ clínico", "vol ∪ idade+sexo"),
    ("disp_template", "disp AD", "disp CN"),
    ("disp_template", "disp CN+AD", "disp CN"),
]

sc = {k: patient_scores_from_path(p, c) for k, (p, c) in arms_x.items()}
# ponytail: sanity — reproduz §2/§6 (vol T1 0.756, idade+sexo 0.542, vol ∪ clínico 0.866)
for k, ref in (("vol T1", 0.7559), ("idade+sexo", 0.5422), ("vol ∪ clínico", 0.8659)):
    assert abs(roc_auc_score(sc[k]["y"], sc[k]["score"]) - ref) < 1e-3, k

rows_x = []
for i, (fam, ka, kb) in enumerate(EXTRA):
    paired = sc[ka].merge(sc[kb], on=["ID_PT", "y"], suffixes=("_a", "_b"))
    assert len(paired) == len(sc["vol T1"]), f"{ka} vs {kb}: {len(paired)} pares"
    seed = cfg.seed + 1100 + 10 * i
    row = paired_comparison_row(
        paired, score_a="score_a", score_b="score_b", label_a="a", label_b="b",
        n_boot=cfg.n_bootstrap, seed=seed,
        permutation_auc_p=permutation_auc_p, n_perm=cfg.n_perm, alpha=ALPHA,
    )
    _, lo99, hi99, p1, _ = bootstrap_auc_diff_test(
        paired["y"], paired["score_a"], paired["score_b"],
        n_boot=cfg.n_bootstrap, seed=seed + 2, ci_level=0.99,
    )
    assert abs(p1 - row["p_bootstrap_one_sided"]) < 1e-12
    row.update({"familia": fam, "arm_a": ka, "arm_b": kb, "ci99_lo": lo99, "ci99_hi": hi99})
    rows_x.append(row)

extra = pd.DataFrame(rows_x)
extra["p_fdr_bh"] = extra.groupby("familia")["p_bootstrap_one_sided"].transform(
    lambda p: apply_bh_fdr(p.to_numpy())
)
for a, lo_col in ((ALPHA, "ci95_lo"), (0.01, "ci99_lo")):
    tag = f"{round(a * 100)}pct"
    extra[f"sig_raw_{tag}"] = (extra["p_bootstrap_one_sided"] < a) & (extra[lo_col] > 0)
    extra[f"sig_fdr_{tag}"] = (extra["p_fdr_bh"] < a) & (extra[lo_col] > 0)
save_table(extra, "stats_complement_extra_48m6m")
display(extra[[
    "familia", "arm_a", "arm_b", "auc_a", "auc_b", "delta_auc", "ci95_lo", "ci95_hi", "ci99_lo", "ci99_hi",
    "p_bootstrap_one_sided", "p_bootstrap_two_sided", "p_fdr_bh", "p_perm_a", "p_perm_b",
    "sig_raw_5pct", "sig_fdr_5pct", "sig_raw_1pct", "sig_fdr_1pct",
]].round(4))

Salvo: Artigo 1 pgirardi/tables/stats_complement_extra_48m6m.csv


,familia,arm_a,arm_b,auc_a,auc_b,delta_auc,ci95_lo,ci95_hi,ci99_lo,ci99_hi,p_bootstrap_one_sided,p_bootstrap_two_sided,p_fdr_bh,p_perm_a,p_perm_b,sig_raw_5pct,sig_fdr_5pct,sig_raw_1pct,sig_fdr_1pct
0,fusao_demo,vol ∪ idade+sexo,vol T1,0.7572,0.7559,0.0013,-0.0320,0.0337,-0.0430,0.0441,0.4563,0.9126,0.4563,0.0002,0.0002,False,False,False,False
1,fusao_demo,vol ∪ idade+sexo,idade+sexo,0.7572,0.5422,0.2150,0.1215,0.3075,0.0918,0.3366,0.0002,0.0004,0.0003,0.0002,0.1644,True,True,True,True
2,fusao_demo,vol ∪ clínico,vol ∪ idade+sexo,0.8659,0.7572,0.1087,0.0598,0.1615,0.0439,0.1771,0.0002,0.0004,0.0003,0.0002,0.0002,True,True,True,True
3,disp_template,disp AD,disp CN,0.5826,0.5404,0.0422,-0.0592,0.1456,-0.0880,0.1894,0.2254,0.4507,0.3363,0.0288,0.1748,False,False,False,False
4,disp_template,disp CN+AD,disp CN,0.5541,0.5404,0.0137,-0.0538,0.0791,-0.0768,0.1005,0.3363,0.6727,0.3363,0.1130,0.1822,False,False,False,False
